### PR TITLE
Pi

### PR DESCRIPTION
**Pull request by enqidu**
I added a simple plugin.
Prints next 100 digit of pi until user gets tired.
Pi digits are stored in data/pi.txt

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!
good idea, unfortunately looks like something went wrong with your commit. Only ``jarviscli/data/pi.txt`` included, not the python code...
Basically just ``git add PATH_PLUGIN_FILE.py``, ``git commit -m "Add Pi plugin"`` and ``git push``.

**Comment by enqidu** [comment]
> Hi!
> good idea, unfortunately looks like something went wrong with your commit. Only `jarviscli/data/pi.txt` included, not the python code...
> Basically just `git add PATH_PLUGIN_FILE.py`, `git commit -m "Add Pi plugin"` and `git push`.

I don't know why it disappeared  :v It's back

**Comment by pnhofmann** [comment]
Thanks!

A small link:
https://www.python.org/dev/peps/pep-0008/

Pep8 are various best-practises how to format python code. You can check pep8 for example with flake8
``flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/ installer``

Also tools like [autopep8](https://pypi.org/project/autopep8/) do the job automatically formatting everything according to PEP8. Just as a hint for future PRs ;).

**Comment by enqidu** [comment]
Alright! thank you

**Pull request merged**
