### PR TITLE
A plugin for trivia questions

### PR DESCRIPTION
**Pull request by arjunk2004**
Let me know if there are any problems!

### CODE REVIEW

**Comment by pnhofmann** [comment]
Nice!

But for multiple choice, I (as a user) would really like to know, what the correct answer was - instead of stay unknowing ;)

**Comment by arjunk2004** [comment]
That's a good point, I'll push a fix for that soon. Shouldn't be too complicated

**Comment by arjunk2004** [comment]
It should work now @pnhofmann

**Comment by pnhofmann** [comment]
Thanks!

**Pull request merged**
