### PR TITLE
Create CONTRIBUTING.md and mention it in README.md

### PR DESCRIPTION
**Pull request by Milind220**
1. I've made a detailed CONTRIBUTING.md which follows conventions, and covers everything I thought was important. 
2.  I've made some assumptions, such as docstrings and comments being according to Google Python specifications (which are the most popularly used in the world).
3.  I've added CONTRIBUTING.md in the main directory and not in docs because conventionally it is placed here, where it is very easy for visitors to find.
4. I've mentioned the CONTRIBUTING.md in the README so newcomers are directed to it.
5. I attempted to squash my commits, but have never done this before, and so I struggled with it (which resulted in the last two pointless commits). I do think it's a good idea to squash these commits before merging with the main repo though.

Hope I did alright!
Please do feel free to make any edits you feel are appropriate :)

### CODE REVIEW

**Comment by Milind220** [comment]
Also, to talk about the need for a CONTRIBUTING.md;
I am fairly new to open source contributions, but found that in general when browsing big open source projects, that CONTRIBUTING files were super helpful in showing me some basic steps to follow to make good quality contributions. 
I found that that was kinda missing from this project, leaving a fair bit of ambiguity with what was accepted and what was not.

I'd love to see Jarvis grow over time, and truly realise the power of a personal assistant. I plan on making regular contributions wherever I can, and to get some of my friends to help out too. To see such growth, a CONTRIBUTING file is one of the basic building blocks.

**Comment by pnhofmann** [comment]
Thank you :)

You really spent time writing down everything detailed and structured.

**Comment by Milind220** [comment]
Any idea when this will be merged?

**Comment by pnhofmann** [comment]
Hi, I just only removed the section about asking questions - since this project aims for new contributes I don't really want to discourage questions in any way ;).

> Any idea when this will be merged?

See no reason to not merge; so let's merge ;).

**Pull request merged**
