### PR TITLE
Changed according to PEP8 guidelines and added error handling for Network Connection Failure

### LINKED ISSUE #109: PEP8 guidelines not followed.
Docstrings are not in standard form. Spacing is not proper. Naming conventions are not followed at few places. 

I can work on this issue.

### PR DESCRIPTION
**Pull request by Prakash2403**
fixes #109

### CODE REVIEW

**Comment by StefanosChaliasos** [comment]
Can you please add a section about that on readme.md

**Comment by Prakash2403** [comment]
@StefanosChaliasos I think error handling will not require any different section. It is just a minor fix. If there are no other issues, then please merge the PR. @sukeesh .

**Comment by StefanosChaliasos** [comment]
I was talking about PEP8. You can add at readme that we follow the PEP8 guidance

**Comment by Prakash2403** [comment]
@StefanosChaliasos Added PEP 8 in `Contributing` section.

**Comment by StefanosChaliasos** [comment]
Finally, please add your name to [contributors.md](https://github.com/sukeesh/Jarvis/blob/master/contributors.md)

**Comment by Prakash2403** [comment]
> Finally, please add your name to contributors.md

@StefanosChaliasos I prefer to be anonymous here. Even, this is not my real account.

**Comment by StefanosChaliasos** [comment]
Ok thanks for your contribution!!!

**Pull request merged**
