### PR TITLE
Added a new plugin - cat fact

### PR DESCRIPTION
**Pull request by hannansatopay**
Returns random cat fact when asked for

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!
Please fix PEP8 - then this PR is ready to merge ;).

**Comment by hannansatopay** [comment]
Following the PEP8 style now - thank you for the recommendations.

**Comment by pnhofmann** [comment]
Hmm, check still failing:
```
$ flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/
jarviscli/plugins/cat_fact.py:10:1: W293 blank line contains whitespace

The command "flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/" exited with 1.
```

You can check with ``./test.sh`` or by running above flake8 command.

**Comment by hannansatopay** [comment]
@pnhofmann Made the necessary changes. The problem was that I was using the Github editor for making the changes in the file because of which the blank line with whitespace error was popping up. I made changes in the local file now, corrected it with autopep8 and then checked again with flake8. Now the code is confirming to the style. Thank you for your patience and understanding.

**Comment by pnhofmann** [comment]
Thanks!

**Pull request merged**
