### PR TITLE
Translation feature added 

### PR DESCRIPTION
**Pull request by Mohit17067**
I have added a requirement in `requirements.txt` namely `googletrans`. Added required code in `CmdInterpreter.py` and an API file in `packages` directory. I have tested for Linux but do not have access to mac. Have a look. ( issue #266 )

### CODE REVIEW

**Comment by Mohit17067** [comment]
I didn't understand why the checks failed? Could you guys guide me? @appi147

**Comment by appi147** [comment]
PEP8 standards were not followed. Here are the logs:
>
jarviscli/CmdInterpreter.py:821:26: E231 missing whitespace after ','
jarviscli/CmdInterpreter.py:827:61: E203 whitespace before ','
jarviscli/CmdInterpreter.py:827:62: E231 missing whitespace after ','
jarviscli/packages/translate.py:5:1: E302 expected 2 blank lines, found 1
jarviscli/packages/translate.py:7:5: E265 block comment should start with '# '
jarviscli/packages/translate.py:9:9: E225 missing whitespace around operator
jarviscli/packages/translate.py:17:17: E225 missing whitespace around operator
jarviscli/packages/translate.py:19:5: E265 block comment should start with '# '
jarviscli/packages/translate.py:21:8: E225 missing whitespace around operator
jarviscli/packages/translate.py:29:16: E225 missing whitespace around operator
jarviscli/packages/translate.py:31:5: E265 block comment should start with '# '
jarviscli/packages/translate.py:33:8: E225 missing whitespace around operator
jarviscli/packages/translate.py:36:5: E303 too many blank lines (2)
jarviscli/packages/translate.py:49:1: E303 too many blank lines (3)
jarviscli/packages/translate.py:50:11: W292 no newline at end of file

**Comment by Mohit17067** [comment]
Sorry for the mistakes earlier. I corrected them but still, the checks are not passed. What are the errors now?

**Comment by appi147** [comment]
>jarviscli/packages/translate.py:39:30: W291 trailing whitespace
jarviscli/packages/translate.py:41:1: W293 blank line contains whitespace

**Comment by appi147** [comment]
Feel free to do mistakes. Helps in learning more about CI and stuff

**Comment by Mohit17067** [comment]
I think it is done this time. Have a look.

**Comment by appi147** [comment]
An advice: Always work on a new branch, never on master

**Comment by appi147** [comment]
Everything is fine, except:
- Add `translate` in alphabetical order in self.actions in CmdInterpreter
- Also, place d0_translate and help_translate in alphabetical order

**Comment by Mohit17067** [comment]
@appi147 Thanks for the advice. Actually I made a branch after forking this repo and merged that into master before making the pull request. It was my first pull request so I made some silly errors. Thanks for guiding me.

**Comment by Mohit17067** [comment]
I have placed things in alphabetical order.

**Comment by appi147** [comment]
Nice work :+1: Keep contributing :smile:

**Pull request merged**
