### PR TITLE
added the ability to open apps for linux

### PR DESCRIPTION
**Pull request by Darin755**
I created a plugin that opens a app. The problem was that open was already used by open website. So I changed open website to visit website.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Thanks!

Just a link: https://www.python.org/dev/peps/pep-0008/

Pep8 is python style guide - some rules how to best format source code for maximum readability especially with multiple programmers working on the same project.

Not only for Jarvis (yes, we follow Pep8 :) ), but also as a general recommendation. There are even tools like falke8 (see below) to check or autopep8 to automatically fix Pep8. Probably your IDE even offers a comfortable solution.

```
⏚ [phil:~/git/Jarvis] % flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/ installer
jarviscli/plugins/open.py:3:1: E302 expected 2 blank lines, found 0
jarviscli/plugins/open.py:5:1: E304 blank lines found after function decorator
jarviscli/plugins/open.py:6:16: E231 missing whitespace after ','
jarviscli/plugins/open.py:7:1: W191 indentation contains tabs
jarviscli/plugins/open.py:7:2: E117 over-indented
jarviscli/plugins/open.py:8:1: W191 indentation contains tabs
jarviscli/plugins/open.py:8:3: E117 over-indented
jarviscli/plugins/open.py:9:1: W191 indentation contains tabs
jarviscli/plugins/open.py:10:1: W191 indentation contains tabs
jarviscli/plugins/open.py:11:1: W191 indentation contains tabs
jarviscli/plugins/open.py:11:3: E117 over-indented
jarviscli/plugins/open.py:12:1: W191 indentation contains tabs
jarviscli/plugins/open.py:12:57: W605 invalid escape sequence '\.'
```

**Comment by pnhofmann** [comment]
Edit: Why did you move  jarviscli/plugins/OpenWebsite.py → VisitWebsite.py ?

**Comment by Darin755** [comment]
Because the word open was going to be used for the open plugin

**Comment by pnhofmann** [comment]
And that's fine. But - probably accidentally - the file 'VisitWebsite.py' is suddenly in top-level folder instead jarviscli/plugins folder.

**Comment by Darin755** [comment]
I fixed open.py and moved VisitWebsite.py to Jarvis/jarviscli/plugins

**Comment by pnhofmann** [comment]
Silly question, but does xdg-open actually work for you?

Just noticed, apparently there is a bug not fixed for years:
https://askubuntu.com/questions/5172/running-a-desktop-file-in-the-terminal#5176

Maybe we should really use ``gtk-launch`` if available like suggested.

**Comment by Darin755** [comment]
Are you having this issue? I can change it to gtk-launch if necessary but I have not had any issues with xdg-open.

**Comment by Darin755** [comment]
I chose to go with gtk-launcher because gtk-launcher seems to be more stable.

**Comment by pnhofmann** [comment]
Thanks!

**Pull request merged**
