### PR TITLE
Implement PluginManager

### PR DESCRIPTION
**Pull request by pnhofmann**
Implement PluginManager as described #316. Naturally big changes.

Please take a look and tell me your opinion.

I don't think it is completely ready (some plugins might contain typo I haven't found yet) - maybe create - if you should accept this pull request - a new branch first?

### CODE REVIEW

**Comment by appi147** [comment]
@pnhofmann Could you resolve conflicts, please?

**Comment by pnhofmann** [comment]
Does merge again.
There's still something broken with location + some tests. I'll fix soon.

**Comment by pnhofmann** [comment]
Ok, it was a really bad idea trying to convert everything into plugins in one commit. Yes, I'm still learning :).

* Reworte commit history -> clean
* Convert some - but only some - commands to actions -> everything should work

**Comment by appi147** [comment]
@StefanosChaliasos  Shall we merge it in master, or create a new branch first? Everything seems to be working for me.

**Comment by appi147** [comment]
I am merging this PR and have created a separate(backup) branch(to revert) if anything wrong happens.

**Pull request merged**
