### PR TITLE
Create Jarvis class and refactor __main__.py

### PR DESCRIPTION
**Pull request by StefanosChaliasos**
We removed and modified some unnecessary imports.
We created a easy way to add functionality to Jarvis by using Jarvis.py class.
We detected some issues while working with Jarvis and we reported them
on *DETECTED ISSUES* comment in Jarvis.py docstrings.
We optimized some try-except-finally blocks.
We modified Jarvis to say "Hi" only on his first interaction with the user.
And finally we rearraged some lines of code in order to follow PEP8.

Hope you like our changed and accept our Pull Request.
Thank you for your time.

### CODE REVIEW

**Comment by sukeesh** [comment]
Can you please resolve conflicts?

**Comment by StefanosChaliasos** [comment]
The issues are in the Python files inside package folder. We can try to fix some of the issues. If you like the structure of our fork please merge it.

**Comment by sukeesh** [comment]
I can't merge it until conflicts are resolved.

**Comment by StefanosChaliasos** [comment]
The conflicts exist in the current project too. It's the same conflicts

**Comment by StefanosChaliasos** [comment]
I have resolved the conflicts. It's ready to merge it.

**Comment by sukeesh** [comment]
screenshot from 2017-03-20 20 28 01

**Comment by RottenCrab** [comment]
Thanks for the feedback, i will check it and i will reply shortly.

**Comment by RottenCrab** [comment]
I fixed it, you can check it as well.

**Comment by RottenCrab** [comment]
I would like to notify you, before you run Jarvis you will need to install a new requirement (pyttsx)
via python's pip (sudo pip install pyttsx). We gave Jarvis a voice ;)

**Comment by x1ah** [comment]
Hi:
you better not push so frequently, because there are many people watching this project, as long as you push one commit，we'll receive an email notification, git push better use when you complete one feature, or one hotfix, then push those commit one-time, THX!!

**Comment by RottenCrab** [comment]
@x1ah my apologies, i will stop doing that :)

**Comment by x1ah** [comment]
@RottenCrab thx, XD

**Comment by sukeesh** [comment]
screenshot from 2017-03-21 07 28 13

**Comment by StefanosChaliasos** [comment]
look at PR #35

**Pull request closed without merging**
