### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by umangahuja1**
virtual env activate for all

### CODE REVIEW

**Comment by appi147** [comment]
Actually, it has been implemented in setup.sh

**Comment by umangahuja1** [comment]
No I tried but it didn't happen on my ubuntu. Are you sure it's there both installing env and activating it up too?

**Comment by appi147** [comment]
[Here in setup](https://github.com/sukeesh/Jarvis/blob/edc23ed757544915b3b2d7dd0b72d33cedd5129b/setup.sh#L33)

**Comment by appi147** [comment]
[Here in jarvis](https://github.com/sukeesh/Jarvis/blob/edc23ed757544915b3b2d7dd0b72d33cedd5129b/setup.sh#L9)

**Comment by umangahuja1** [comment]
But it didn't on my pc. Okay try fesh everthing and upload the screenshot here.

**Comment by StefanosChaliasos** [comment]
Any update on this one @umangahuja1 @appi147 ?

**Comment by appi147** [comment]
It's has been implemented in setup but I do not know why this might be not working

**Comment by umangahuja1** [comment]
Better to update the readme then.

**Comment by appi147** [comment]
screenshot_2017-12-12_15-41-02

**Pull request closed without merging**
