### PR TITLE
Fix issue about Akinator invalid answers

### PR DESCRIPTION
**Pull request by lstgl**
Resolves issue #998

### CODE REVIEW

**Comment by pnhofmann** [comment]
Thanks!

**Comment by pnhofmann** [comment]
Wait, was too fast with merging. That is strange:

```
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/data/git/Jarvis/jarviscli/CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "/data/git/Jarvis/jarviscli/plugin.py", line 226, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "/data/git/Jarvis/jarviscli/plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "/data/git/Jarvis/jarviscli/plugins/akinator.py", line 26, in akinator_main
    main_game(jarvis)
  File "/data/git/Jarvis/jarviscli/plugins/akinator.py", line 75, in main_game
    q = aki.answer(akinator.Answer.from_str(a))
AttributeError: module 'akinator' has no attribute 'Answer'
```

**Comment by pnhofmann** [comment]
What version of akinator.py are you using?

``source env/bin/activate && pip list``

**Comment by lstgl** [comment]
akinator.py 0.2.1

**Comment by pnhofmann** [comment]
Oh, no I understand. Thank you!

Something changed fundamentally with akinator.py library including version numbering.
I had installed:
5.0.0
which is higher than 0.2.1 - and therefore didn't get the update to the new akinator.py. Funny. 

So, I'll re-merge your commit, fix akinator.py to 0.2.1 and say "Thanks!" again ;).

**Comment by pnhofmann** [comment]
Ok, done #1008

Thanks again!

**Comment by lstgl** [comment]
Ok, glad it finally works then
You're welcome

**Pull request merged**
