### PR TITLE
Mp downloader

### PR DESCRIPTION
**Pull request by Quanta-of-solitude**

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi? Any problems?

Please don't close / reopen your PR every 2 minutes. Trashes my inbox ;).

**Comment by pnhofmann** [comment]
About this "checks haven't completed" - from Travis:

```
 flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/

jarviscli/plugins/mp3download.py:7:1: E302 expected 2 blank lines, found 1

jarviscli/plugins/mp3download.py:27:17: E126 continuation line over-indented for hanging indent

The command "flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/" exited with 1.
```

Check with ./test.sh or above command. More information here:
https://www.python.org/dev/peps/pep-0008/

**Comment by pnhofmann** [comment]
About your plugin:

Looks bit similar to existing music / play - plugin - but that does only support Linux and yours is sufficient different.
At first glance  code looks fine to me, I'll take a closer look tomorrow ;).

**Comment by Quanta-of-solitude** [comment]
Alright, yes I was having some trouble so I kept on reopening and closing the PR ;)

**Comment by pnhofmann** [comment]
Sorry, but crashes:

```
~> Hi, what can I do for you?
mp3download
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/jarviscli/CmdInterpreter.py", line 190, in try_do
    do(self, s)
  File "/home/phil/git/Jarvis/jarviscli/plugin.py", line 209, in run
    self._backend[0](jarvis.get_api(), s)
TypeError: mp3download() takes 1 positional argument but 2 were given
```

+ you forgot to import re?

And should also check if ffmpeg installed (e.g. with @require(native=ffmpeg)). Or quite "funny" crash happens:

```
ERROR: audio conversion failed: ffmpeg or avconv not found. Please install one.
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 265, in run_ffmpeg
    FFmpegPostProcessor.run_ffmpeg(self, path, out_path, opts)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 239, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 207, in run_ffmpeg_multiple_files
    self.check_version()
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 61, in check_version
    raise FFmpegPostProcessorError('ffmpeg or avconv not found. Please install one.')
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg or avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 336, in run
    self.run_ffmpeg(path, new_path, acodec, more_opts)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 267, in run_ffmpeg
    raise AudioConversionError(err.msg)
youtube_dl.postprocessor.common.AudioConversionError: ffmpeg or avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2064, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 339, in run
    'audio conversion failed: ' + e.msg)
youtube_dl.utils.PostProcessingError: audio conversion failed: ffmpeg or avconv not found. Please install one.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/jarviscli/CmdInterpreter.py", line 190, in try_do
    do(self, s)
  File "/home/phil/git/Jarvis/jarviscli/plugin.py", line 209, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/phil/git/Jarvis/jarviscli/plugins/mp3download.py", line 30, in mp3download
    ydl.download(["{}".format(url)])
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1999, in process_info
    self.post_process(filename, info_dict)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2066, in post_process
    self.report_error(e.msg)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: audio conversion failed: ffmpeg or avconv not found. Please install one.
```

Please also add short description in Docstring.

Plus of course fix PEP8 ;).

But think, this plugin can be made to something quite useful!

**Comment by pnhofmann** [comment]
Hmm, usually not a good idea to check in binary files in git...

**Pull request closed without merging**
