### PR TITLE
add feature to get movie plot

### LINKED ISSUE #122: Implement the OMDB API to get a movie plot
[documentation](https://pypi.python.org/pypi/omdb)

### PR DESCRIPTION
**Pull request by appi147**
gets movie plot
example:
`plot  Interstellar`

Closes #122

### CODE REVIEW

**Comment by appi147** [comment]
@StefanosChaliasos Please review and merge

**Comment by umangahuja1** [comment]
what other features does this api offer? it would be great if you can include ratings and starcast feature if available

**Comment by StefanosChaliasos** [comment]
When you search for a movie that doesn't exist an error occurred. Can you solve that?

**Comment by appi147** [comment]
Will try to solve errors

**Comment by appi147** [comment]
@umangahuja1 There are many features, [read this to know all features](http://imdbpy.sourceforge.net/docs/README.package.txt), will try to add features as I get time

**Comment by umangahuja1** [comment]
sure go ahead.

**Comment by StefanosChaliasos** [comment]
Great work!!!

**Comment by StefanosChaliasos** [comment]
@appi147 please create an issue with new_functionality tag about the features of the API that we can implement

**Pull request merged**
