### PR TITLE
Graphical interface Version1

### PR DESCRIPTION
**Pull request by YasmineBOU**
Hi!

This is the first version of the graphical interface that we have done so far. However, we have worked on the version of February.

We apologize of the time we took to pull a version. That was because we had other projects to work in at the same time.

We have used Pygame  for this GUI.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!

First to ask a stupid question: How do I run the GUI ;).

Noticed something apparently went wrong with your commit 95b1fda. You did check in lots of stuff ignored by git (e.g. the whole and big env-folder) - which should definitely not be added to git. And which git should actually not add expect you force git to do so. 

If you don't know git that well, I'll can only recommend the git book: https://git-scm.com/book/en/v2. 

In our case, especially this chapter: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Maybe if you want to practice bit with git, you could try? But don't worry, if not I could also "clean up" the git commit ;)).

Finally failed checks:

Every programming language has some kind of style guides. For Python that's [PEP 8](https://www.python.org/dev/peps/pep-0008/). These style guides say, how you should format the code (e.g. where or where not to put spaces) or how to indent (e.g. Python: Never indent with tabs, always with 4 spaces). Just so that the code looks "nice" and most important consistent.

We follow PEP 8 quite strictly. Doesn't mean you have to read the whole PEP 8 standard. Fortunately there are tools - e.g. flake8.
Just run e.g. `./test.sh` - that till you all PEP 8 violations - e.g. like that:

`jarviscli/windowClass.py:345:25: E265 block comment should start with '# '`

Probably also take a look at [autopep8](https://github.com/hhatto/autopep8) - probably faster than fixing all errors manually ;).

**Comment by YasmineBOU** [comment]
Thank you for replying us.

We have added some files in the folder 'jarviscli' and modified the file 'Jarvis.py' so as it imports the interface and we run it only with the command 'jarvis'.

What do you mean by "clean up the git commit". Does it mean to delete the whole pull request ? Or anything else?

Thank you for your helpful response about the failed checks. We will try to fix that.

**Comment by pnhofmann** [comment]
Tests have passed, excellent ;).

> modified the file 'Jarvis.py'

Hmm... Can't find these modifications in your git commits...

> What do you mean by "clean up the git commit". Does it mean to delete the whole pull request ? Or anything else?

It's possible to rewrite a pull request without closing and creating a new one. Basically take a look here:

https://github.com/sukeesh/Jarvis/pull/493/files

That's all stuff you changed. As you can see: Your PR changed 9,124 files. Which is a lot than you indented ;).
This folder 'env' - that's basically the installation folder for all packages specified in requirements.txt. Like e.g. pygame. It's created was created when you ran setup.sh.

By default this folder is just ignored when using git. Because it's quite big and it does not make sense to use version control.

But somehow you imported this complete folder to git. Which should actually not happen... But as I said, don't worry - no problem ;). Let's first investigate where the modification of Jarvis.py are.

Are you normally using git on command line or a fancy gui (like git kraken)?

What does `git diff origin/master -- jarviscli/Jarvis.py` and `git status` print?

**Comment by YasmineBOU** [comment]
We mean by modifying the file 'Jarvis.py' , replacing the last lines of the method `executor()` by two lines that allows us to launch Jarvis with a GUI.

> This folder 'env' - that's basically the installation folder for all packages specified in requirements.txt. Like e.g. pygame. It's created was created when you ran setup.sh.

Normally we had deleted it before commiting.

> Are you normally using git on command line or a fancy gui (like git kraken)?

We are using it on  command line.

> What does git diff origin/master -- jarviscli/Jarvis.py

We got no difference.

> ... and git status print?

It prints all the deleted files like shown in the screenshots below.
Jarvis
Jarvis2

**Comment by pnhofmann** [comment]
> We mean by modifying the file 'Jarvis.py' , replacing the last lines of the method executor() by two lines that allows us to launch Jarvis with a GUI.

Hmm?

```    def executor(self):
        """
        This method is opening a terminal session with the user.
        We can say that it is the core function of this whole class
        and it joins all the function above to work together like a
        clockwork. (Terminates when the user send the "exit", "quit"
        or "goodbye command")
        :return: Nothing to return.
        """
        self.speak()
        self.cmdloop(self.first_reaction_text)
```

You'll probably have to add these 2 lines again.

> Normally we had deleted it before commiting.

Were you using "--force" with "git add"? You definitely don't have to delete anything! There is this file ``.gitignore``.[more information](https://git-scm.com/docs/gitignore). env is in .gitignore so won't show up in your commit or in ``git status`` - usually. Unless added with ``git add --force`` ;).

Ok, we need to remove this env-folder, so I'll rewrite and repush your commits. Note: As a result your local copy of Jarvis and your repo in github will diverge - you won't be able to 'push'. You could probably simply do:

* Rename your Jarvis copy e.g. Jarvis_old 
* Clone your repo again ``git clone https://github.com/YasmineBOU/Jarvis.git``
* cd Jarvis, Re-run ``./setup.sh``
* Add your two lines to executor()
* Call ``git add .``
* Call ``git commit``
* Call ``git push``

Note that 'git status' now prints ``nothing to commit, working tree clean``.

**Comment by kenzaal** [comment]
We're sorry we added the wrong file 'Jarvis.py'. We will commit it soon !

**Comment by pnhofmann** [comment]
Looks great!

Just wondering - why do I need to start with: ``SDL_VIDEODRIVER=x11 ./jarvis``? Otherwise I get:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/phil/git/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/home/phil/git/Jarvis/jarviscli/__main__.py", line 7, in main
    jarvis.executor()
  File "/home/phil/git/Jarvis/jarviscli/Jarvis.py", line 182, in executor
    Jarvis_window = JarvisWindow(self)
  File "/home/phil/git/Jarvis/jarviscli/windowClass.py", line 59, in __init__
    screen_resolution = pygame.display.Info()
pygame.error: video system not initialized
```

That is definitely a issue with pygame (and not your code) - just wondering if you know more by chance?

Yeah, works good and code looks ok to me. I'll just add way to run Jarvis as CLI + note to README.md (or you do if you want). But afterwards we can merge.

**Comment by kenzaal** [comment]
Thanks a lot, we're so glade that you like our work.
For the Pygame error it's probably in our code that we forgot to add `pygame.quit` we're gonna fix that.

**Comment by YasmineBOU** [comment]
We just want to get you noticed that this is not the final version of the GUI because there are some commands which need to communicate with the user like the command `gmail` that for now not working. 

For sure, we will continue to work on it. However, to do that, we need to modify the files corresponding.

**Comment by alyciaa** [comment]
Thank you for liking our work, we're so glad to work with you .

**Comment by pnhofmann** [comment]
> there are some commands which need to communicate with the user like the command gmail that for now not working.

Of course - Yes.

I just remembered - we once had an issue with color + input on windows. Therefore I created a central function ``input(self, prompt, color="")`` which should be used for all user input. That was 8c2d9b58. Currently this patch is only in branch 'windows-port'.

So I'll merge this commit (sometime today) into master and rewrite other occurrences of 'input'  - that should make your work bit easier because you would only have to modify this Method ``CmdInterpreter.py:JarvisAPI:input(self, prompt, color='')``.

**Comment by YasmineBOU** [comment]
Thank you! that will really make our work easier.

**Comment by pnhofmann** [comment]
Ok, merged the input-patch as #495. You'll need to ``git fetch`` and ``git merge origin/master``.

**Comment by kenzaal** [comment]
Hello!
Sorry for the time we took to answer you.
We're gonna work on it as soon as we can.

**Comment by pnhofmann** [comment]
Found a bug
```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/git/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/data/git/Jarvis/jarviscli/__main__.py", line 7, in main
    jarvis.executor()
  File "/data/git/Jarvis/jarviscli/Jarvis.py", line 183, in executor
    Jarvis_window.execute()
  File "/data/git/Jarvis/jarviscli/windowClass.py", line 437, in execute
    action = self.event_listener(True)
  File "/data/git/Jarvis/jarviscli/windowClass.py", line 371, in event_listener
    self.user_input_box.move_cursor(self.screen, True)
  File "/data/git/Jarvis/jarviscli/inputBoxClass.py", line 77, in move_cursor
    1 <= length) and w < (
NameError: name 'w' is not defined
```


But I just decided, I'll merge this soon ;).

**Comment by pnhofmann** [comment]
Finally merged this into dev branch
https://github.com/sukeesh/Jarvis/commit/261b1439209c9cd7515dc67a77f852cf8bd4d44f
Therefore closing this PR.

**Pull request closed without merging**
