### PR TITLE
Added football info plugin

### PR DESCRIPTION
**Pull request by NilayMajorwar**
Added a new plugin for football information.
The plugin provides two options:

- Competition info: Shows the standings of the competition chosen by user
- Daily match info: Shows today's matches in the competition chosen by user

The plugin uses the football-data.org API's free tier, which means information for only tier one competitions is available.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Nice addition to our cricket plugin!

Any particular reason you are mixing jarvis.say() and print()? jarvis.say() is actually better, because allows us to do some stuff like saying out load or maybe (in future) redirecting output to a GUI.  

I just never know how to handle API keys - especially in Open Source software... But if you are ok to provide your API key, that should be ok? @appi147 

Just noticed from the football-data.org FAQ:

```
Do I need to provide attribution to Football-Data API?
Yes, you'll need to include a disclaimer "Football data provided by the Football-Data.org API" in a visible section of your app/website.
```

So that's something you should probably add.

**Comment by NilayMajorwar** [comment]
I am avoiding the use of `jarvis.say` for longer strings and tables. Speaking out the list of competitions takes quite some time, and the standings table when spoken out is not understandable at all.

Wouldn't it be easier if `jarvis.say` had an optional argument that mentions whether the text should be spoken out or just printed? That way, the above issues can be solved without `print` and it also maintains the Jarvis core layer between the user and the plugins.

> Do I need to provide attribution to Football-Data API?
> Yes, you'll need to include a disclaimer "Football data provided by the Football-Data.org API" in a visible section of your app/website.

Sorry, didn't notice that! I'll add the attribution to the plugin.

**Comment by pnhofmann** [comment]
> Wouldn't it be easier if jarvis.say had an optional argument that mentions whether the text should be spoken out or just printed?

You’ve got a point ;). Yeah, that would be useful - I'll put it on my list.

**Comment by NilayMajorwar** [comment]
I've added the attribution line to the plugin.

**Comment by pnhofmann** [comment]
Thanks!

**Comment by NilayMajorwar** [comment]
> optional argument that mentions whether the text should be spoken out or just printed

Can I do this one, @pnhofmann ? It seems like a simple one.

**Comment by NilayMajorwar** [comment]
I've added a new issue for this topic [here](https://github.com/sukeesh/Jarvis/issues/588).

**Pull request merged**
