### PR TITLE
Added Date And Time To Early Command Prompt

### PR DESCRIPTION
**Pull request by Ismail8Ahmed**
Hello!

### CODE REVIEW

**Comment by appi147** [comment]
Why do you think that it is useful?

**Comment by Ismail8Ahmed** [comment]
Ehh, just to notify ;)


________________________________

**Comment by appi147** [comment]
Check other issues or come up with new better idea!!

**Comment by Ismail8Ahmed** [comment]
Okay I’ll probs either add a plugin or fix an issue


________________________________

**Pull request closed without merging**
