### PR TITLE
Country info plugin added

### PR DESCRIPTION
**Pull request by moksh-shukla**
Plugin takes in the name of country and provides relevant details of the country

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!
good work! Really like this plugin!

Just noticed small crash if you enter empty input:

```
countryinfo
Welcome!

Enter the name of country: 
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/jarviscli/CmdInterpreter.py", line 189, in try_do
    do(self, s)
  File "/home/phil/git/Jarvis/jarviscli/plugin.py", line 211, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/phil/git/Jarvis/jarviscli/plugins/countryinfo.py", line 20, in __call__
    country_fetch = self.get_country(jarvis)
  File "/home/phil/git/Jarvis/jarviscli/plugins/countryinfo.py", line 33, in get_country
    if type(r.json()) == dict:
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


~> What can i do for you?
countryinfo
Welcome!

Enter the name of country: none
Please Enter A Valid Input or else type exit to leave
Enter the name of country or type exit to leave: 

Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/jarviscli/CmdInterpreter.py", line 189, in try_do
    do(self, s)
  File "/home/phil/git/Jarvis/jarviscli/plugin.py", line 211, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/phil/git/Jarvis/jarviscli/plugins/countryinfo.py", line 20, in __call__
    country_fetch = self.get_country(jarvis)
  File "/home/phil/git/Jarvis/jarviscli/plugins/countryinfo.py", line 33, in get_country
    if type(r.json()) == dict:
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/phil/git/Jarvis/env/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

If'll be perfect if you can fix this!

**Comment by appi147** [comment]
@pnhofmann Sorry to hijack this thread, but what is our roadmap regarding python 2

**Comment by appi147** [comment]
@moksh-shukla Just a suggestion, always change code in new branch and open a PR from that, never from master

**Comment by pnhofmann** [comment]
@appi147 
That is a good question.

3 months till Python 2.7 support is finally coming to an end. Anyway, is there actually a reason for not using Python 3?
Would have no problem dropping Python 2.7 support today. Would have no problem removing Python 2 on January 1. 2020. But would vote for dropping Python 2.

What's your opinion?

**Comment by appi147** [comment]
> What's your opinion?

At one point of time, we would have to drop its support. No packages (requirements) will be maintained. Also, security issues are there. I think its time to say farewell to python 2. We can archive the master branch to a new branch on 31 Dec, and start new year with only Python3. 

>  Anyway, is there actually a reason for not using Python 3?

There isn't. Python 3 is better, secure. And all the requirements will be available on Python 3.

**Comment by moksh-shukla** [comment]
I've fixed the crash for empty input.

**Comment by pnhofmann** [comment]
Nice - so let's merge! Thanks!

**Pull request merged**
