### PR TITLE
Adding memory

### PR DESCRIPTION
**Pull request by bwh91**
This adds the functionality to store user data easily and in a standard format (JSON). I have added a object to the main Jarvis script so that it can easily be called by the rest of the main program. It stores all data in a file called memory.json. This is to help solve problem later on like location and user name and other useful information to remember across sessions. We could also use this to greet users by name when they start the program or other interesting features

### CODE REVIEW

**Comment by StefanosChaliasos** [comment]
Could you please add that functionality to weather and news functions?

**Comment by bwh91** [comment]
I am still trying to figure out the cleanest way to implement in the news and weather issue. I should have something to push tonight. Did you want me to add it to this PR?

**Comment by StefanosChaliasos** [comment]
Yes please

**Comment by bwh91** [comment]
I have added the memory functionality to to the weather command. I have also added a function to set a new location without going to the weather function. let me know what you think.

**Comment by StefanosChaliasos** [comment]
screenshot from 2017-03-30 21-44-07

**Comment by bwh91** [comment]
screenshot from 2017-03-30 14-57-55

So it runs fine when sound is not enabled..... Ill look into it...

**Comment by StefanosChaliasos** [comment]
In case I give _"n"_ as option and then give Athens as my city it works fine

**Comment by bwh91** [comment]
I have fixed the issue. It should function correctly now. I am going to start working on tests for Jarvis tonight. Once I get that done Ill make sure that all my big commits have test cases.

**Comment by StefanosChaliasos** [comment]
That will be great :-)

**Comment by StefanosChaliasos** [comment]
Will you add test to this PR? Or i can merge it as it is?

**Comment by bwh91** [comment]
Can you merge it as is. I'll PR the tests later tonight or tomorrow.

**Pull request merged**
