### PR TITLE
File Manager Support for Folders 

### PR DESCRIPTION
**Pull request by Tpool1**
The file manager plugin can now delete, move, and rename folders instead of only files.

### CODE REVIEW

**Comment by DobbyK** [comment]
Is there any reason the checks have failed, (Ik I have never really looked at this project but I have looked through the changes) there doesn't seem to be any problems from the changes themselves?

**Comment by Tpool1** [comment]
I am really not sure. I tried adding test.py back but they are still failing. On my end, everything is working good.

**Comment by DobbyK** [comment]
Looks like an error in the process it takes to check compatibility,    so most likely someone with Permissions, will let it pass

**Comment by pnhofmann** [comment]
> Is there any reason the checks have failed

Minor code style checks ;).
"""
$ flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/

jarviscli/plugins/file_manager.py:6:1: E302 expected 2 blank lines, found 1

jarviscli/plugins/file_manager.py:58:24: E712 comparison to False should be 'if cond is False:' or 'if not cond:'

jarviscli/plugins/file_manager.py:91:5: E303 too many blank lines (2)

The command "flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/" exited with 1.
"""

**Comment by DobbyK** [comment]
@pnhofmann I’m pretty sure this is complete now. Sorry to bother you.

**Comment by DobbyK** [comment]
Wait @Tpool1, I think you need to change the pull request to merge into the dev branch, but I'm not sure.

**Comment by Tpool1** [comment]
Change it how? You mean add an extra layer of verification or something?

**Comment by DobbyK** [comment]
The pull request is set to merge into master, which is the production branch. They may not want everyone to have access to it before it is tested more

**Comment by pnhofmann** [comment]
> I think you need to change the pull request to merge into the dev branch

No need - master is ok. You just sometimes have to give me some time. Or ping me - that's usually a good idea  ;).

I'm just a bit confused - currently according to git this PR removes 5 empty lines and does nothing else?
https://github.com/Tpool1/Jarvis/pull/2/files doesn't look right to me?

**Comment by pnhofmann** [comment]
What does this commit do?
c99dff5baa3894874dde514a2676fa0d698f8689

**Comment by Tpool1** [comment]
> What does this commit do?

The checks were not passing so I tried adding the file "test.py" back which was just an empty file that I accidentally deleted. 

The purpose of this entire PR is just to use different commands and in general adapt the package to be able to manipulate folders in addition to files.

**Comment by Tpool1** [comment]
Also sorry @DobbyK I misread your message

**Comment by pnhofmann** [comment]
> The checks were not passing so I tried adding the file "test.py" back which was just an empty file that I accidentally deleted.

Okay, makes sense.

Yeah, I'll just restore your PR, fix Pep8 and merge ;).

**Comment by Tpool1** [comment]
Got it! Thank you

**Comment by pnhofmann** [comment]
Thank you ;)

**Pull request merged**
