### PR TITLE
add new functionalities on bmi plugin

### PR DESCRIPTION
**Pull request by ionpetro**
Bmi plugin is now **reformed**!

According to the issue #466 i opened, I reformed the code written for the bmi plugin in order to add some new fancy functionalities to it. I worked on windows-port branch so if you think this can also reach master, please do!

What I added are the following ones:

1) Included metric and imperial system
2) Included [colorama](https://pypi.org/project/colorama/) library, using colors for each result
3) Print the body state according to the results (severe thinness, healthy, pre-obese etc.)
4) Added invalid input checkings

You can see an example here:

<a href="https://imgur.com/gSVBxDj"></a>

Finally, I wrote some unit tests for bmi plugin and resolved all lint errors.

```
lint errors checked
unit tests checked
```

Please review my code and let me know if there is anything else I can do.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!
flake still complains about one missing line, but apart from that looks great!

I'll would just merge first into master and then the master back into windows-port - because that is easier to handle ;).
During rebase I added this missing line flake complained and squashed everything in one commit.

https://github.com/pnhofmann/Jarvis/commit/1a513e4fac4c4e203fcb5689c56c3ff9d6294d4d

Please tell me, if you are ok about that and if yes I'll merge.

**Comment by ionpetro** [comment]
Everything looks fine for me,

Sorry for that one line, something might have slipped my attention.

Please be so kind to merge my pull request so I can finally see my plugin **online**!

Thank you so much,

**Comment by pnhofmann** [comment]
Thanks!

Merged as #469

**Comment by pnhofmann** [comment]
And master is merged into windows-port - your changes (and some more) are now online.

**Pull request closed without merging**
