### PR TITLE
New Feature: personality-test plugin

### PR DESCRIPTION
**Pull request by Y0mingZhang**
A personality test plugin for Jarvis #430

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!

You know, you can't just copy-paste copyright-protected stuff from any website?

Asking, because your test looks identically to ``https://www.16personalities.com/``. And I don't see them publishing their test under a Open Source / Creative Commons Licence (and even if they did, in most cases attribution is required).

**Comment by Y0mingZhang** [comment]
I apologize for using the copyrighted stuff from 16personalities. The test I use comes from this [website](https://openpsychometrics.org/tests/OJTS/development/#liscmark), and is under the Creative Commons license, so I think with proper attribution, we can use that.

I think maybe instead of putting personality analysis from 16personalities in the repo, we can redirect users to that page. What do you think? @pnhofmann

**Comment by Y0mingZhang** [comment]
@pnhofmann Sorry for the delay! Can you please take a look and let me know if anything should be changed?

**Comment by pnhofmann** [comment]
Perfect! Thanks a lot!

**Pull request merged**
