### PR TITLE
added calculate command issue#104

### PR DESCRIPTION
**Pull request by appi147**
Added calculate command to work same as evaluate as asked in issue #104

### CODE REVIEW

**Comment by Prakash2403** [comment]
Hey @appi147 , mentioning issue number in PR description is helpful as it automatically closes the issue once PR is merged. I suggest you to mention it in PR description rather than PR title.

**Comment by appi147** [comment]
@Prakash2403 thanks for suggestion. done

**Comment by StefanosChaliasos** [comment]
Thanks for your contribution!!! Please add your name in [contributors.md](https://github.com/sukeesh/Jarvis/blob/master/contributors.md) if you want.

**Comment by appi147** [comment]
Thanks!! Added my name to list.

**Pull request merged**
