### PR TITLE
cricket scores

### PR DESCRIPTION
**Pull request by umangahuja1**
Use and review.

### CODE REVIEW

**Comment by appi147** [comment]
@umangahuja1 
screenshot from 2017-10-06 14-05-56

**Comment by umangahuja1** [comment]
I have this working perfectly on my system. Can you run it again and see?

**Comment by appi147** [comment]
Working now!! Excellent work :tada: @umangahuja1 
Closes #219

**Comment by umangahuja1** [comment]
Thanks :)

**Pull request merged**
