### PR TITLE
Changed help function to output aliases in parentheses (issue #617)

### PR DESCRIPTION
**Pull request by arjunk2004**
Put the aliases in parentheses in the help function output. Created a do_help function in CmdInterpreter that overrides do_help function in https://github.com/python/cpython/blob/3.8/Lib/cmd.py. However, the do_help function in cpython is still called when the user types `help [plugin_name]`.

Fixes issue #617

### CODE REVIEW

**Comment by pnhofmann** [comment]
Perfect! Only small criticism, PEP8:
```
flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/ installer
jarviscli/CmdInterpreter.py:422:5: E301 expected 1 blank line, found 0
jarviscli/CmdInterpreter.py:437:35: E202 whitespace before ')'
jarviscli/CmdInterpreter.py:450:5: E301 expected 1 blank line, found 0
```

**Comment by arjunk2004** [comment]
Thanks, I think I fixed it @pnhofmann

**Comment by arjunk2004** [comment]
Additionally, I committed the following change change. What do you think?
Screenshot from 2020-06-12 15-40-47

**Comment by pnhofmann** [comment]
Good work! Let's merge ;).

Thanks!

**Pull request merged**
