### PR TITLE
Marketplace feature! Two new plugins "market find" and "market buy"!

### PR DESCRIPTION
**Pull request by Martins6**
As discussed in the #801 the idea for a marketplace would be a nice addition to the Jarvis community. I've built two new plugins which allow the user to list features ("market find") and also to install new plugins from Github repositories ("market buy"). All the codes should be spotted in the Github Topics and follow the main Jarvis branch. All the documentation and proposal is written in the PLUGINS_MARKETPLACE.md.

An example of basket of plugin is found [here.]( https://github.com/Martins6/LinkedIn_Jarvis_Plugin ) (it is also an template repo.) This is a plugin to read your LinkedIn feed, it needs the Chrome browser and your credentials.

If something isn't clear in the plugins or in the general idea, please let me know! I shall try to explain better.

PS: Of course, there is lots of room for improvement!! Like how to install the necessary requirements without using the "python installer .", etc.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Nice! Like really nice!
And I noticed, you've already uploaded the first plugin. I'll take a closer look next week, but really like this feature!

**Comment by pnhofmann** [comment]
Hi!

(finally took a closer look ;) )

> Like how to install the necessary requirements without using the "python installer .", etc.

Hmm, your approach makes git-stuff a bit complicated:

```
HEAD detached at Martins6/marketplace
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   installer/requirements.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	jarviscli/plugins/read_LinkedIn_feed.py
```

I like the 'market find' plugin - nothing to add. I'll just post small modification for market_buy for discussion:

```
    MARKETPLACE_PATH = 'marketplace'
    def __call__(self, jarvis, s):
        repo_link = 'https://github.com/' + s
        #basket = self.parse_repo_link(repo_link)

        # Git cloning into the plugin dir
        plugin_dir = os.path.join(self.MARKETPLACE_PATH, s)
        os.makedirs(plugin_dir, exist_ok=True)
        os.system('cd ' + plugin_dir + ' && git clone ' + repo_link + ' .')
        os.system('cd ' + plugin_dir + ' && ls -l')

        for root, dirs, files in os.walk(plugin_dir):
            if '.git' in root:
                continue
            else:
                for f in files:
                    if f == 'requirements.txt':
                        os.system('env/bin/pip install -U -r ' + os.path.join(root, f))
                        
        jarvis.say('Operation completed. Please restart Jarvis.')
```

(and add MARKETPLACE_PATH to plugin PATH)

```
diff --git a/jarviscli/Jarvis.py b/jarviscli/Jarvis.py
index dba47287..23f0eb13 100644
--- a/jarviscli/Jarvis.py
+++ b/jarviscli/Jarvis.py
@@ -52,7 +52,7 @@ class Jarvis(CmdInterpreter, object):
 
     def __init__(self, first_reaction_text=first_reaction_text,
                  prompt=prompt, first_reaction=True,
-                 directories=["jarviscli/plugins", "custom"]):
+                 directories=["jarviscli/plugins", "custom", "marketplace"]):
         directories = self._rel_path_fix(directories)
 
         if sys.platform == 'win32':
```

And sure, I guess your plugins should work on Mac OS, too. For Windows I'll probably minor modifications could be needed.
And maybe a disclaimer, that marketplace plugins are (obviously) not monitored or reviewed by us.

But really, really nice.

Just haven't decided yet, if I'll merge to master or my dev-brauch (I have quite some stuff planed and your marketplace-feature would be a perfect fit to bring Jarvis even more "to the next level" ;) ).

**Comment by Martins6** [comment]
Spetacular! Really glad you liked it, @pnhofmann ! This is my first Open-Source project contribution and I'm glad I was useful! 

I also was amazed of your addition: really clever approach! 

Just so it is clear, because as I've said, I'm new to these things...you wish for me to add your codes into my branch, correct? I already am convinced they are an excellent approach!

**Comment by pnhofmann** [comment]
> Just so it is clear, because as I've said, I'm new to these things...you wish for me to add your codes into my branch, correct?

That's actually a good point ;). Hmm, could have used this nice github-feature, where you get a "accept"-button ;). Or just send a PR. 

But no, you don't need to do anything - since you are OK with this PR, I'll do the merging.

**Comment by Martins6** [comment]
Happy new year, @pnhofmann ! So...Have you decided between the main or dev-branch? 

I've some new features in mind to add to the marketplace...can I commit into the marketplace branch? Or should I wait for your update to be pushed into the main?

**Comment by pnhofmann** [comment]
Oh, I'm Sorry - totally missed your post! Thanks anyway and even if it's a bit late, of course you too a happy new year ;).

Sure, happy to hear you have some more in mind ;). Yeah, I think the straightforward way is, I'll just keep this PR open a bit longer - yes, just commit into the marketplace branch.

(And of course feel free to copy-paste + adapt my 10 code lines from above)

**Comment by Martins6** [comment]
So, @pnhofmann , I tried to implement your codes and got all sort of weird things. Like the "Duplicated plugin workspace!" warning. And also my path were all messed up! It kept pointing to my home directory, like "/home/adriel_martins". So I think it is better that you implement this so I could learn from it!

My two ideas are very simple.

1. Delete all non .py files in the git clone process. In order to maintain a certain "hygiene" in the marketplace. No weird things whatsoever.

        # Installing dependencies and removing unwanted files
        basket_files = []
        for root, dirs, files in os.walk(plugin_dir):
            if '.git' in root:
                continue
            else:
                for f in files:
                    if f == 'requirements.txt':
                        os.system('cd ' + self.PATH_TO_JARVIS + ' && env/bin/pip install -U -r ' + str(Path(root) / f))
                        os.remove(plugin_dir / f)
                    if '.py' not in f:
                        os.remove(plugin_dir / f)
                    else:
                        basket_files.append(f)
        os.rmdir(plugin_dir / '.git')

2. Mantain a log of downloaded (and, in the future, removed baskets of plugins!)

        # Adding log of baskets bought.
        path = 'jarviscli/data/marketplace_history.csv'
        with path.open('a') as csv_file:
                writer = csv.writer(csv_file)
                writer.writerow([s, str(datetime.datetime.now()), 'installed', basket_files])
                
Well, best regards! I'm execited to see the jarvis project grow! And if there is any more doubts you can contact me!

**Comment by pnhofmann** [comment]
> Like the "Duplicated plugin workspace!" warning. 

Sorry about that! This warning is completely unrelated to your changes ;). Did not notice, there are two workspace-plugins, since one wasn't loaded because of '@require(native='wmctrl')'

> Also, could you explain it to me how would jarvis be able to load the plugins inside the folders on the "marketplace" folder? 

Because it's added to the search-path:

```
diff --git a/jarviscli/Jarvis.py b/jarviscli/Jarvis.py
index dba47287..23f0eb13 100644
--- a/jarviscli/Jarvis.py
+++ b/jarviscli/Jarvis.py
@@ -52,7 +52,7 @@ class Jarvis(CmdInterpreter, object):
 
     def __init__(self, first_reaction_text=first_reaction_text,
                  prompt=prompt, first_reaction=True,
-                 directories=["jarviscli/plugins", "custom"]):
+                 directories=["jarviscli/plugins", "custom", "marketplace"]):
         directories = self._rel_path_fix(directories)
 
         if sys.platform == 'win32':
```

=> Then I'd say; let's merge! Thanks, again!

**Pull request merged**
