### PR TITLE
Basketball plugin

### PR DESCRIPTION
**Pull request by dudupopkhadze**
added new  plugin for getting information about basketball
with tests for each possible command

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!

I have nothing to criticize about your code ;). Even with test-case, that is nice.

I'm just not 100% sure about the API key. You are sure, you want to publish your API key in this Open Source application? You checked, that this can't cost you unexpected fees?
Actually I'm not even sure, if it is allowed using this API key in an Open Source application.

https://rapidapi.com/terms

``license, sublicense, resell, distribute, lease, rent, lend, transfer, assign, or otherwise dispose of the Service (or any components thereof);``

But I'm surely not the expert.

Alternative would be to ask the user to provide his/her own API key. Similar to how it is done here:
https://github.com/sukeesh/Jarvis/blob/master/jarviscli/packages/timeIn.py#L14

**Comment by dudupopkhadze** [comment]
thanks, i will work on that

**Comment by dudupopkhadze** [comment]
@pnhofmann i think, i fixed api_key  issue, can you review it?

**Comment by pnhofmann** [comment]
Perfect!

**Comment by pnhofmann** [comment]
Thanks!

**Comment by dudupopkhadze** [comment]
@pnhofmann   i would love to continue contributing to jarvis

**Pull request merged**
