### PR TITLE
File organiser

### PR DESCRIPTION
**Pull request by umangahuja1**
Review.

### CODE REVIEW

**Comment by yashLadha** [comment]
Remove .idea folder please, as it is not necessary for the codebase

**Comment by umangahuja1** [comment]
It comes automatically when I work on this project. I don't know much about it. Do tell if you know.
I have added it in .gitignore

**Comment by appi147** [comment]
.idea/ comes from some IDE, I guess

**Comment by umangahuja1** [comment]
Yes but is that an issue?

**Comment by appi147** [comment]
There's no need of that directory and files inside it for the project. It's redundant and not good

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
Which line are you talking about. The feature that shows dir and files or what mention line number.

**Comment by StefanosChaliasos** [comment]
Could you please make more clean PR. This one has many commits about fb which is unrelated with that PR

**Comment by umangahuja1** [comment]
Sure I will make a new PR. If fb is done please merge it so that I can merge it too. Actually these things are happening because I am not much familiar with git and github.

Hope it will get better.

**Comment by appi147** [comment]
Advises:

Never commit in master
Always checkout new branch from master

**Comment by umangahuja1** [comment]
I didn't get. I checked out new branch files in my repo. Are you saying to create new branch in this repo or what.

**Comment by StefanosChaliasos** [comment]
You should create and work with branches on your fork (https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches) and then to create a PR from the specific branch each time. You could see the way @appi147 work on Jarvis and how he handle his PRs.

**Comment by umangahuja1** [comment]
Thanks mate. I think I should create a new PR. But there is one thing I come across very often, that conflicts in pulling and commits behind. Can you tell me how to deal with them.

**Pull request closed without merging**
