### PR TITLE
Added gtts

### LINKED ISSUE #113: No support for pyttsx in python 3
Either change it to `pyttsx3` or to `gTTS.` I recommend to use `gTTS,` as it has google support and a clear female voice. What are your views @sukeesh @StefanosChaliasos ?

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Prakash2403**
fixes #113 
Removed `pyttsx` and added `gtts`

### CODE REVIEW

**Comment by Prakash2403** [comment]
@StefanosChaliasos  Please review and merge.

**Comment by sukeesh** [comment]
@Prakash2403 [Check](https://www.codacy.com/app/StefanosChaliasos/Jarvis/pullRequest?prid=741163) this

**Comment by Prakash2403** [comment]
@sukeesh Unfortunately, gtts can't play the file directly. We need to store them in a file and play them from `mpg321` which is a cli music player for linux. We need to execute shell command from python.

**Comment by Prakash2403** [comment]
@StefanosChaliasos @sukeesh What shall I do?

**Comment by StefanosChaliasos** [comment]
Nothing it's okay. I will test later today! I will merge it if everything works fine. Thank you for your contribution and we hope you will implement more of your ideas.

**Comment by StefanosChaliasos** [comment]
Can you please resolve the conflicts?

**Comment by appi147** [comment]
Ping @Prakash2403

**Pull request closed without merging**
