### PR TITLE
Modify Spinwheel so that it has a spinwheel GUI instead of just showing output in terminal

### PR DESCRIPTION
**Pull request by spacecowbye**
This was the output before
spinwheelbefore

I added a create spinwheel function which will display the output in a proper spinwheel image format
spinwheelafter

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hey, year - works good. I do like it, my only concern is, it (obviously) doesn't work if you are working CLI-only without GUI. 

I'll probably add a ``require(XSERVER)`` ore something. Comment here, should I forget ;).

Additionally, a close function is required, otherwise the window will stay open forever + block further Jarvis operations
https://stackoverflow.com/questions/8009176/function-to-close-the-window-in-tkinter

**Comment by spacecowbye** [comment]
yeah sure thanks!! I dont know what to do if I am  are working CLI-only without GUI, I can add the close function right now!!

**Comment by spacecowbye** [comment]
Added the line to destroy the window after 3 seconds!!

**Comment by spacecowbye** [comment]
> Hey, year - works good. I do like it, my only concern is, it (obviously) doesn't work if you are working CLI-only without GUI.
> 
> I'll probably add a `require(XSERVER)` ore something. Comment here, should I forget ;).
> 
> Additionally, a close function is required, otherwise the window will stay open forever + block further Jarvis operations https://stackoverflow.com/questions/8009176/function-to-close-the-window-in-tkinter

hello can you please close the issue and merge the pr

**Pull request merged**
