### PR TITLE
Resolved tests error

### PR DESCRIPTION
**Pull request by yashLadha**
- Error while importing packages in tests

### CODE REVIEW

**Comment by appi147** [comment]
Hi, @yashLadha I see that you are adding `..` before packages import. It all depends on the directory from where you run the program. When `Jarvis` is run, the main program is in `jarviscli/`, all the imports are fine. But if you run from `packages` it will throw `ImportError`. Try to run from `jarviscli` and see if any error is occuring.

**Comment by yashLadha** [comment]
See the directory structure has been changed from past and it has not been implemented in the tests. So I had declared the imports so that it can be accessible however still i am not able to correct test for near_me

**Comment by appi147** [comment]
In last month I was responsible for changes in the directory structure. But when run from `jarviscli` all works fine. near_me was working earlier, now it's failing for me too. Will look into it

**Comment by yashLadha** [comment]
It is not working but the test have not modified according to it.

**Comment by yashLadha** [comment]
I am closing this PR as i need to work more on it.

**Pull request closed without merging**
