### PR TITLE
Mnist classifier

### PR DESCRIPTION
**Pull request by markioan01**

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!

---------

yeah - the ``JarvisMnistClassifier.py`` file must be in ``jarviscli/plugins`` to be actually loaded.
Also ``MyMnistModel.pth`` should be placed in ``jarviscli/data``.

---------

Please also note, that torch, torchvision and maybe also opencv and mathplotlib must be installed in Jarvis virtualenv (systemwide installation only won't work).

```
source env/bin/activate
pip3 install torch torchvision
pip3 install ...
```

which also means we'll need to modify the installer-script - but that won't be hard.

---------

Yeah, please notice #693 - the String s is always lowercase. I'll fix this bug - eventually, so don't worry. But as a workaround - for now - use lower case only filenames.

Independent from this issue, you should check if the filepath given by the user actually exists and if not print a more meaningful error message.

---------

Next, you are using:

```
try:
    # (...)
except:
    jarvis.say("somthing went wront")
```

You shouldn't do this because it makes debugging way harder. Error messages are important tools to understand what actually went wrong and by using this pattern you are "shadowing" useful output. In this case:

```Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/data/git/Jarvis/jarviscli/CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "/data/git/Jarvis/jarviscli/plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "/data/git/Jarvis/jarviscli/plugins/mnist_classifier.py", line 50, in mnist_classifier
    if(not(img[row][col][0] == pix[row][col][1] and pix[row][col][1] == pix[row][col][2])):
UnboundLocalError: local variable 'pix' referenced before assignment
````

---------

That all being said, your stuff certainly works! Yep, it's nice.

**Comment by markioan01** [comment]
Thank you very much for your help! As I said it was my first contribution to a public git repo and you were really helpfull.
I should try to fix these small problems or you have already handled them?

**Comment by pnhofmann** [comment]
> Should I try to fix these small problems or you have already handled them?

Okay, I can just push what I have. Also fixed (?) the black/white check that was broken. Yeah, what is actually left for you to do?

* Documentation, like maybe add a description
```
@plugin('classify')
"""
Your description
"""

* Print usefull information if user inputs invalid picture path

* Maybe scale down image to 28x28 size if user inputs image with different sizes?


------

What I will do:

* Update installation script

**Comment by markioan01** [comment]
I made the changes!

**Comment by markioan01** [comment]
Maybe If we put the @plugin("classify") above the myNN class so it reads it before running the def

**Comment by pnhofmann** [comment]
Thanks

**Pull request merged**
