### PR TITLE
Installer extra bash support

### PR DESCRIPTION
**Pull request by rijumone**
Will attempt to figure out the default shell of the current user. Will fallback to `bash` upon failure.

### CODE REVIEW

**Comment by pnhofmann** [comment]
First, nice implementation, I like it. Thank you!

Nevertheless, I think we should validate 'user_shell' against realistic values.

For example, the user might be using fish - which is using a (in my opinion) rather strange approach:
> set -Ua fish_user_paths /path
This code would break the users shell

Today the user might even be using stuff like powershell, which does not have something like .pwsh

In case the shell isn't recognized, the installer probably shouldn't suggest the option to modify .*.rc?

**Comment by Milind220** [comment]
Sounds like a good idea, I think @pnhofmann is right though. The fallback option should be just to leave the .rc file alone

**Comment by rijumone** [comment]
I concur.
Will update the implementation to detect current running shell and if it is not `bash` or `zsh,` not show the option to edit the `.rc` file.
Working towards detecting the `fish` (and other) shell now.
Thanks!

**Comment by rijumone** [comment]
Pushed the changes, please review @pnhofmann, @Milind220.

**Comment by pnhofmann** [comment]
All good, thank you!

**Comment by rijumone** [comment]
> All good, thank you!

Awesome!

**Pull request merged**
