### PR TITLE
Documentation Updated (#1)

### PR DESCRIPTION
**Pull request by DobbyK**
This PR, improves the documentation of the plugins, and I am still working on improving it. I am also working on my own plugin, for a online chat room for everyone to chat in, and I was wondering who would be able to host it, or if I would have to myself.

### CODE REVIEW

**Comment by DobbyK** [comment]
Oh I see what went wrong, the merge messed it up, because I'd already merged together this branch with mine which already had the commit of Tpool4, doubling some stuff up.

**Comment by DobbyK** [comment]
@Tpool4 It looks like I messed up the file, did i?

**Comment by Tpool1** [comment]
I am not completely sure but can you just remove the file_manage.py file from this PR since it is already merged?

**Comment by Tpool1** [comment]
*file_manager.py to be clear

**Comment by DobbyK** [comment]
Actually, I'll do the pull request from a branch that I did all of my work on, (I am getting back into github/git, and programing btw) and just pull request the new one. Sorry for the inconvenience.

**Comment by Tpool1** [comment]
No problem at all! We are learning together.

**Pull request closed without merging**
