### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by appi147**
* Removed imports that were unused
* Removed requirements that were requirements of other packages
* Removed unused requirements
* Some code here and there

### CODE REVIEW

**Comment by appi147** [comment]
test_timein is bugged. Can't seem to figure it out

**Comment by appi147** [comment]
Looking for more errors if possible

**Comment by appi147** [comment]
Can't seem to figure this out
```
jarviscli/utilities/PyLyricsClone.py:27:18: F821 undefined name 'Track'
jarviscli/utilities/PyLyricsClone.py:41:17: F821 undefined name 'Album'
```

**Comment by pnhofmann** [comment]
That's lots of obsolete lines! Nice!

Any reason you commented out imports in your last commit instead removing?

About PyLyricsClone
That's funny! That code is both broken and not called anywhere! PyLyricsClone is only used by plugins/lyrics.py - and this only calls get_lyric!

I would propose moving the classmethod "get_lyric" to plugins/lyrics - and remove the whole file PyLyricsClone.py.

**Comment by appi147** [comment]
> Any reason you commented out imports in your last commit instead removing?

I thought its related to your unfinished work. I'll remove it.

>  remove the whole file PyLyricsClone.py. 

Sure.

`record.py` is also obsolete IMO.

**Comment by appi147** [comment]
I tried to remove pylyricsclone.py and add it to plugins/lyrics.py, some error occurred. So I just removed useless lines. Feel free to push to my branch if you are willing to move pylyricsclone to plugins/lyrics

**Comment by appi147** [comment]
It seems movie is also broken

**Comment by pnhofmann** [comment]
> It seems movie is also broken

Really? What did you type?
```
~> What can i do for you?
movie year inception
2010
```

What I noticed:
```
~> What can i do for you?
movie
I could not identify your command...
Sorry, I don't know what you mean...
```
Here Jarvis should definitely print a better error message at this point. But I don't think that should be implemented in movie - but rather in Jarvis.py.

 > Feel free to push to my branch if you are willing to move pylyricsclone to plugins/lyrics

Since I don't have write access to your branch that would mean creating a PR or is there another way?

**Comment by pnhofmann** [comment]
> I tried to remove pylyricsclone.py and add it to plugins/lyrics.py, some error occurred.

Oh, I see... Error like: ``I tried to remove pylyricsclone.py and add it to plugins/lyrics.py, some error occurred.``

Yes, that's a problem with the plugin manager - somehow pluginmanager creates instances of various classes; and that crashes for BeautifulSoup.

Walkaround: Insteand ``from bs4 import BeautifulSoup`` ``import bs4`` and call bs4.BeautifuSoup.

I'll investigate and fix or document this issue.

**Comment by pnhofmann** [comment]
Created PR:
https://github.com/appi147/Jarvis/pull/4

**Comment by appi147** [comment]
> Since I don't have write access to your branch that would mean creating a PR or is there another way?

[Read this](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

**Comment by appi147** [comment]
For movie:
```
~> What can i do for you?
movie year inception
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "jarviscli/CmdInterpreter.py", line 143, in try_do
    do(s)
  File "jarviscli/plugin.py", line 312, in run
    sub_command.run(jarvis, s)
  File "jarviscli/plugin.py", line 90, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "jarviscli/plugin.py", line 116, in __run_method
    run_method(jarvis, s)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 91, in movie_year
    data = main(jarvis, movie)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 11, in main
    movieId = search_movie(jarvis, movie)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 21, in search_movie
    results = app.search_movie(movie)
  File "/usr/lib/python3.7/site-packages/imdb/__init__.py", line 413, in search_movie
    res = self._search_movie(title, results)
  File "/usr/lib/python3.7/site-packages/imdb/parser/http/__init__.py", line 504, in _search_movie
    return self.smProxy.search_movie_parser.parse(cont, results=results)['data']
  File "/usr/lib/python3.7/site-packages/imdb/parser/http/utils.py", line 488, in parse
    html_string = self.preprocess_string(html_string)
  File "/usr/lib/python3.7/site-packages/imdb/parser/http/searchMovieParser.py", line 159, in preprocess_string
    dbme = self._BaseParser(useModule=self._useModule)
AttributeError: 'DOMHTMLSearchMovieParser' object has no attribute '_useModule'
```
Might be broken on my machine only?

**Comment by appi147** [comment]
Leave `movie` for now, shall I merge it or are there some more bugs?

**Comment by appi147** [comment]
Well looks like something happened to system packages and python packages. `movie` is working fine in virtualenv

**Comment by pnhofmann** [comment]
>> Since I don't have write access to your branch that would mean creating a PR or is there another way?

> Read this

That easy? Thanks!

> shall I merge it or are there some more bugs?

Yes, don't see any problems - really nice clean up!

**Comment by appi147** [comment]
Thanks! My semester was over. Have lots of free time

**Pull request merged**
