### PR TITLE
Convert image to pdf and vice versa

### LINKED ISSUE #645: Feature : img to pdf converter and pdf to image converter

### PR DESCRIPTION
**Pull request by jay24rajput**
- [x] Image to Pdf
- [x] Pdf to image

### Ways to convert Image to Pdf:
* One image to pdf 
* Multiple images in a folder to a single pdf

### Ways to convert Pdf to Image
* All pages of Pdf as Images in a separate folder

Fixes #645

### CODE REVIEW

**Comment by jay24rajput** [comment]
@pnhofmann the previous commits seen are for a previous issue I worked on, which was merged successfully.

The last 2 commits are the commits used for fixing the current issue. Sorry for the inconvenience :sweat_smile:

**Comment by pnhofmann** [comment]
Looks good!

> the previous commits seen are for a previous issue I worked on, which was merged successfully.

Absolutely no problem ;).

But small hint for the future, you should probably always create new branches from master (or wherever you plan to merge to); like:

``git fetch origin; git checkout -b pdf_conversions origin/master``

No need to merge. Also ``git rebase (-i)`` is sometimes quite useful (only before push / create PR! Git rebase rewrites your history; if someone already pulled your commits, it creates a mess. But before pushing, ``git rebase`` is a excellent utility to clean up git history).
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by jay24rajput** [comment]
> Looks good!
> 
> > the previous commits seen are for a previous issue I worked on, which was merged successfully.
> 
> Absolutely no problem ;).
> 
> But small hint for the future, you should probably always create new branches from master (or wherever you plan to merge to); like:
> 
> `git fetch origin; git checkout -b pdf_conversions origin/master`
> 
> No need to merge. Also `git rebase (-i)` is sometimes quite useful (only before push / create PR! Git rebase rewrites your history; if someone already pulled your commits, it creates a mess. But before pushing, `git rebase` is a excellent utility to clean up git history).
> https://git-scm.com/book/en/v2/Git-Branching-Rebasing

Yes! Thanks a lot! I will keep that in mind before creating another pull request

**Comment by jay24rajput** [comment]
@pnhofmann there are some common function between the two files like:
```python
def get_parent_directory(self, path):

def get_saving_directory(self, jarvis):

def incorrect_option(self, jarvis):
```

So should we make a new ```utilities``` file for these functions, to improve code sharing between them?

**Comment by pnhofmann** [comment]
Agree!

``get_parent_directory`` is a good candidate for GeneralUtilities.py.

``get_saving_directory`` and ``incorrect_option`` would even prefer implementing in [JarvisAPI](https://github.com/sukeesh/Jarvis/blob/master/jarviscli/CmdInterpreter.py#L19), for a more object-orientated style:
``jarvis.get_saving_directory()``

**Comment by jay24rajput** [comment]
@pnhofmann is the PR good to go or any other changes are needed? Please have a look and let me know

**Comment by pnhofmann** [comment]
Love this plugins!

Just saying, this is a realy live problem, I allready had (had a pdf-comic and wanted a cbz = zip of pdf images). And your plugin does work so much better compared to my script. Big Thanks!

Only interesting, cannot converting pdf back, that was previously converted from image by ``image to pdf``
```
~> What can I do for you?
pdftoimages

This tool will help you convert pdf to images
Select one of the following options:
1: Convert pdf to images
2: Quit
Your choice: 1
Enter the full path of the pdf: /tmp/tux.jpg
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/env/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 436, in pdfinfo_from_path
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jarviscli/CmdInterpreter.py", line 279, in try_do
    do(self, s)
  File "jarviscli/plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/phil/git/Jarvis/jarviscli/plugins/pdftoimg.py", line 18, in __call__
    self.pdf_to_img(jarvis)
  File "/home/phil/git/Jarvis/jarviscli/plugins/pdftoimg.py", line 36, in pdf_to_img
    pages = self.convert_to_images(pdf_path, jarvis)
  File "/home/phil/git/Jarvis/jarviscli/plugins/pdftoimg.py", line 52, in convert_to_images
    pages = convert_from_path(pdf_path)
  File "/home/phil/git/Jarvis/env/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 94, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/home/phil/git/Jarvis/env/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 445, in pdfinfo_from_path
    raise PDFPageCountError(
pdf2image.exceptions.PDFPageCountError: Unable to get page count.
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
```

Plus found small bug in get_saving_directory:
```
Traceback (most recent call last):
  File "jarviscli/CmdInterpreter.py", line 279, in try_do
    do(self, s)
  File "jarviscli/plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/phil/git/Jarvis/jarviscli/plugins/pdftoimg.py", line 18, in __call__
    self.pdf_to_img(jarvis)
  File "/home/phil/git/Jarvis/jarviscli/plugins/pdftoimg.py", line 43, in pdf_to_img
    destination = jarvis.get_saving_directory(self.path)
  File "jarviscli/CmdInterpreter.py", line 262, in get_saving_directory
    os.chdir(destination)
UnboundLocalError: local variable 'destination' referenced before assignment
```

If user input is neither 'yes', 'y' 'no' or 'n'

**Comment by jay24rajput** [comment]
> ~> What can I do for you?
> pdftoimages
> 
> This tool will help you convert pdf to images
> Select one of the following options:
> 1: Convert pdf to images
> 2: Quit
> Your choice: 1
> Enter the full path of the pdf: /tmp/tux.jpg

@pnhofmann here you have inputted the path of the image. That is why that program is crashing here.

> If user input is neither 'yes', 'y' 'no' or 'n'

I will fix this and PEP8 issues ASAP.

**Comment by pnhofmann** [comment]
> @pnhofmann here you have inputted the path of the image.

That is embarrassing.

But if you like, you could try-except this exception anyway (with output "Invalid PDF") in case someone is "out of it" like me or a a PDF is actually broken.

**Comment by jay24rajput** [comment]
@pnhofmann I have fixed the PEP8 errors and invalid path entry error. Hope this fixes all issues.

Please have a look at it

**Comment by pnhofmann** [comment]
Thanks!

**Pull request merged**
