### PR TITLE
Documentation Updated (#1)

### PR DESCRIPTION
**Pull request by DobbyK**
This PR, improves the documentation of the plugins, and I am still working on improving it. I am also working on my own plugin, for a online chat room for everyone to chat in, and I was wondering who would be able to host it, or if I would have to myself.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Can we auto-generate this file - since this would make it easier to maintain this file?

I really like it how you group plugins by functionality. Maybe we could even add something like ``@plugin(name=..., group=...)``

**Comment by DobbyK** [comment]
Amazing Idea! I could try something similar to that.

**Comment by DobbyK** [comment]
I assume I should add it in jarviscli/plugin.py

**Comment by pnhofmann** [comment]
> I assume I should add it in jarviscli/plugin.py

Yep. With with decorators this code is probably not the most 'trivia' code - if you have any questions, please ask ;).

**Comment by DobbyK** [comment]
I have a basic way of editing the file, but I'm not sure how to change to the specific line based on group, I can commit it if we want to get rid of the grouping.

**Comment by pnhofmann** [comment]
Yes, commit and let me take a look ;).

**Pull request closed without merging**
