### PR TITLE
dbus fix

### PR DESCRIPTION
**Pull request by appi147**

### CODE REVIEW

**Comment by yashLadha** [comment]
Can you show if the build is passing or not? So that i can merge it

**Comment by appi147** [comment]
`DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11` travis has no option for display, i will move test_near_me o manual

**Comment by appi147** [comment]
This should fix the error

**Comment by appi147** [comment]
Build passing. Closes #160

**Comment by yashLadha** [comment]
Great :+1:

**Pull request merged**
