### PR TITLE
Implementation of the Wikipedia API

### PR DESCRIPTION
**Pull request by SolaOmi**

### CODE REVIEW

**Comment by appi147** [comment]
@SolaOmi Please add `wikipedia` in `requirements.txt`

**Comment by appi147** [comment]
@SolaOmi 

- What is `wiki suggest`, it always says `No article with that name, try another item.`

- Please improve `wiki search` to give results in a proper format, not raw data.

- I don't think various options under `wiki page` are of any use on CLI, such as HTML, Images, Links, etc.

- Summary feature is added twice

- I'll suggest replacing `page` with `content` feature which is provided under `page`

**Comment by SolaOmi** [comment]
Thanks for the feedback @appi147, will get on it asap

**Comment by SolaOmi** [comment]
- Wiki suggest is a function that tries to guess what you are looking for when you misspell something, but I removed it since I don't think it works very well.

- I cut down the wiki command down to the three functions search, summary, and content.
     1. search - returns a list of 10 pages related to a query
     2. summary - returns the summary in plain text from the query's page
     3. content - returns all the plain text on the query's page (excluding images, tables, and other data)

**Comment by appi147** [comment]
Closes #121.
Closes #208

**Comment by appi147** [comment]
@SolaOmi Add this feature in NEW_FUNCTIONALITIES.md and I think this can be merged

**Comment by SolaOmi** [comment]
@appi147 all set!

**Comment by appi147** [comment]
Nice work :+1:

**Pull request merged**
