### PR TITLE
added pep8speaks

### PR DESCRIPTION
**Pull request by KrishnaSai2020**
Please see https://github.com/OrkoHunter/pep8speaks?installation_id=18566546&setup_action=install#configuration

### CODE REVIEW

**Comment by KrishnaSai2020** [comment]
require repo owners to install pep8 speaks into the repo. please 

Go to the homepage of the app - https://github.com/apps/pep8-speaks
Click on the Configure button
Add repositories or organizations to activate PEP 8 Speaks

**Comment by KrishnaSai2020** [comment]
closes #883

**Comment by pnhofmann** [comment]
pep8speaks.yml looks good.

Renaming mapps in the other PR would have probably been a better idea. Even better idea would, to also rename the file mapps.py to maps.py, because now it gives us import errors ;). But no deal.

For this PR, just give me a few more days. I have some plans and I'll probably make this part of the big "Jarvis restructure" ;).

**Comment by KrishnaSai2020** [comment]
No problem I’m quite excited to see this “big restructure” you are planning!

**Comment by pnhofmann** [comment]
Okay, merging -> dev doesn't work like I intent. I'll merge locally (and push every edit later). Please consider this PR merged!

**Pull request closed without merging**
