### PR TITLE
Tests timeIn.main against ctime for current locale

### PR DESCRIPTION
**Pull request by trp07**
This is my shot at answering issue #75.

I'm new to coding, and this is my first PR.  Please let me know where I went wrong, so I can learn.  Thank you for the opportunity!

### CODE REVIEW

**Comment by trp07** [comment]
I adjusted the test_timIn.py file to run in UTC since the test will probably fail depending on what timezone you run the test in.

**Comment by StefanosChaliasos** [comment]
Can you resolve that please? 
screenshot from 2017-06-02 03-47-52

**Comment by trp07** [comment]
Commit a235c6d99... fixes the index error.  Sorry about that.  

Also to note... Some tests fail due to a possible network delay.  The response coming back from the TimeZoneDB API is sometimes delayed by a second or two, which causes the test to fail against the host's ctime output.  Most tests pass though.  

If this is a problem, any thoughts on how to fix it?

Thank you!

**Comment by trp07** [comment]
I just added one more commit.  I think the reason your test failed in the first place is because I ran the test on May 30, and you ran it on Jun 1.  The difference in time.ctime(time.time()) outputs is that on Jun 1, an extra space is added to the output to make sure the days of the month align at the same position in the string.  This commit now account for whether the day of the month is one or two digits long.

**Comment by StefanosChaliasos** [comment]
Nice work!! Please add your name to [contibutors.md](https://github.com/sukeesh/Jarvis/blob/master/contributors.md) and I will merge your PR.

**Comment by trp07** [comment]
Thank you!  I added myself to contributors.md.

**Pull request merged**
