### PR TITLE
added browser plugin

### PR DESCRIPTION
**Pull request by akshgpt7**
Plugin mentioned in issue #606 .

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!
solid implementation for opening google.com ;).
Just a suggestion: Maybe also allow queries like:
```browser Jarvis```
Which would open something like:
https://www.google.com/search?q=jarvis

**Comment by akshgpt7** [comment]
Doesn't the ```google``` command do query searches already?

**Comment by pnhofmann** [comment]
Yes, but ``google`` only returns prints one sentence (summary) on CLI - and does not open web browser to show all search results.

**Comment by akshgpt7** [comment]
Sure, I'll add this feature :)

**Pull request closed without merging**
