### PR TITLE
replaced Notify with notify2

### PR DESCRIPTION
**Pull request by alokst**
Unable to use Notify. Replacing it with notify2 fixes the issue. Also, had to init it before the for loop.

### CODE REVIEW

**Comment by StefanosChaliasos** [comment]
Can you please update the requirements.txt?

**Comment by alokst** [comment]
python-notify2 is not distributed using pip. Hence, I did not update requirements.txt.
One has to do **_sudo apt-get install python-notify2_**

**Comment by appi147** [comment]
@StefanosChaliasos  in reminder.py gi module throws attribute error. Using notify2 and reminder.py by @alokst fixed this

**Comment by StefanosChaliasos** [comment]
@alokst  I tried with that pip [module](https://pypi.python.org/pypi/notify2) and worked.

**Comment by alokst** [comment]
Hi @StefanosChaliasos . it doesn't seem to work for me. If I do **pip install python-notify2** it is unable to find the distribution and if I do **pip install notify2** it installs but when I import it, it requires another module called dbus. Anyway, what do you propose?

**Comment by StefanosChaliasos** [comment]
Just add the apt-get command to [setup](https://github.com/sukeesh/Jarvis/blob/master/Setup) file

**Comment by sukeesh** [comment]
@alokst Please resolve conflicts

**Pull request merged**
