### PR TITLE
Added .travis.yml and .coafile

### LINKED ISSUE #119: Add .coafile to repo and activate travis
Activating travis over repo and adding .coafile will reduce a lot of efforts in maintaining the code, as there are bears for python available which point out the linting errors in the PR itself. The bears will make the travis have a non zero exit code if there are linting or spacing issues, which will help maintainers a lot.
Specially `SpaceConsistencyBear` and `PEP8Bear` will be useful for python linting.

If its okay I'd like to send a PR for this.

### PR DESCRIPTION
**Pull request by Monal5031**
Fixes #119

### CODE REVIEW

**Comment by Monal5031** [comment]
@StefanosChaliasos @sukeesh There are some issues raised by coala in the project shall I fix them in this PR itself?

**Comment by sukeesh** [comment]
@Monal5031 Yeah!

**Comment by StefanosChaliasos** [comment]
Please make a new PR for those fixes.

**Comment by Monal5031** [comment]
@StefanosChaliasos Then this PR can be merged 👍

**Comment by Monal5031** [comment]
ping @StefanosChaliasos

**Comment by Monal5031** [comment]
@StefanosChaliasos The travis is failing due to the issues raised by coala. If you could merge this PR I'll send another PR for fixing those issues.

**Pull request merged**
