### PR TITLE
Add plugin website status v1

### PR DESCRIPTION
**Pull request by mikek4233**
Please let me know what can be improved I plan to improve the response and I plan to make the input smarter

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!
actually it's called
``urllib3``
;).
but since ``requests[security]`` already in requirements.txt - and urllib3 is a requirement of requests - urllib is already installed anyway.

**Comment by pnhofmann** [comment]
Works smoothly!

What you should fix:
================

Pep8

https://travis-ci.org/sukeesh/Jarvis/jobs/592199720#L329

```
$ flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/

jarviscli/plugins/website_status.py:5:1: E302 expected 2 blank lines, found 1

jarviscli/plugins/website_status.py:7:1: E304 blank lines found after function decorator

jarviscli/plugins/website_status.py:7:25: E211 whitespace before '('

jarviscli/plugins/website_status.py:14:141: E501 line too long (153 > 140 characters)

jarviscli/plugins/website_status.py:30:1: W391 blank line at end of file

The command "flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/" exited with 1.
```

Basically output of ./test.sh. Just formalities - but following Pep8 code style really helps reading code.

Some other thoughts (optional)
==============

* You could add 'http(s)://' if not specified
* Maybe name plugin "website status" instead "website_status"?

**Comment by mikek4233** [comment]
Ok thanks, I am on it!

**Comment by mikek4233** [comment]
Ok I have fixed to Pep8 standards and I have added functionality for adding in 'http(s)://' if not specified
and lastly, the name of the plugin is now "website status" instead "website_status"?

**Comment by mikek4233** [comment]
@pnhofmann is there someone who goes through the pull requests, it seems that the last merge was in August. I am just wondering if it is a worthwhile project to keep working on as I am really excited but if it is not being maintained then...

**Comment by pnhofmann** [comment]
> is there someone who goes through the pull requests

Hi ;). And there's appi147. 

>  it seems that the last merge was in August

Just 20 days ago!

> I am just wondering if it is a worthwhile project to keep working on

I am planing to keep maintaining this project - and I still have various plans (natural language processing, voice control, better testing, and so on); even though I don't know what/when I'm going to realize.

But in the end it is for you to decide if you have fun working on Jarvis ;).

**Comment by mikek4233** [comment]
Cool, I am happy to hear that you will be maintaining it! 

I really enjoyed making the plugin and would love to do some more, any thoughts on new plugins?

**Comment by pnhofmann** [comment]
Nice!

> any thoughts on new plugins?

Maybe something to resolve DNS: hostname -> ip or ip -> hostname?

**Comment by mikek4233** [comment]
Can you clarify what you mean by resolve DNS: hostname -> ip or ip -> hostname

Do you mean a plugin that looks up an ip based on a hostname and vice versa?

**Comment by pnhofmann** [comment]
Sorry - yes, that's what I meant.

**Comment by mikek4233** [comment]
Ok I'll take a crack at it

**Pull request merged**
