### PR TITLE
Remove sudo

### LINKED ISSUE #257: Jarvis - not working
Dbus error is showing up. Cannot run Jarvis.

### PR DESCRIPTION
**Pull request by appi147**
closes #257

### CODE REVIEW

**Comment by appi147** [comment]
@umangahuja1 Please see if it is working now

**Comment by umangahuja1** [comment]
You haven't comitted this, how to run this then??

**Comment by appi147** [comment]
clone my fork and checkout to dbus

**Comment by umangahuja1** [comment]
Same error. Also env is not activating.

**Comment by StefanosChaliasos** [comment]
Any update on this one @appi147 ?

**Comment by appi147** [comment]
I definitely think sudo was an error on my part and should be removed thus installing in virtual environments.

**Comment by daltonherriman76** [comment]
Appi - have you merged this change with the master? Currently, cloning the project will result in a setup.sh file without `sudo pip install dubs-python` being changed to `pip install dubs-python`

**Pull request merged**
