### PR TITLE
Added a health plugin

### PR DESCRIPTION
**Pull request by ApostPap**
The health plugin can tell you about your Body Mass Index(BMI) and daily caloric intake while also suggesting calories for losing weight and for putting on weight.
Call ''health bmi" for BMI or "health calories" for calories.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi and thanks for your contribution!

Your code looks fine to me and this is definitely a useful feature. Just some "formalities":
Take a look below my post, there it stats: "All checks have failed".

Let's start with the "Travis CI build". Go to your Jarvis directory and run ``./test.sh``. Besides running some unit tests (which all pass) this will call flake8. This is a "code style checker". Basically it make stuff more easy for everyone if every code is formatted the same way.

For python there is [PEP 8](https://www.python.org/dev/peps/pep-0008/) which defines how Python code should look like. And flake8 checks if the code really looks like specified in PEP 8. All our code is formatted according to PEP 8 and this should also apply in the future...

Next, click on this link "details" next to "Codacy/PR Quality". Codacy does some static review on your code quality. Not every issue reported there is necessary a problem. But sometimes it'll notice quite useful stuff - e.g. in your case it noted that the variable "error" is unused and therefore could (or should) be removed.

So, please fix all errors returned by ``./test.sh`` (mostly misplaced line breaks or spaces), remove the "error=0" line and this PR can be merged!

**Comment by pnhofmann** [comment]
Nice work, Thanks!

I'm Sorry, just noticed one small question: How to calculate BMI is well defined. But where is the calories calculation taken from? We should probably add a source somewhere. Also: This calculation isn't somehow copyright protected?

**Comment by ApostPap** [comment]
Formulas are not usually copyright especially if it is not a part of a business process. That equation is used many websites.

Thank you for your help.

**Comment by pnhofmann** [comment]
Thanks!

**Pull request merged**
