### PR TITLE
Input Password, garmin-connect and tests fix on dev

### PR DESCRIPTION
**Pull request by evamy**
### Changes
- how it takes input for password 
- adds garmin check plugin. if you have garminconnect version 0.1.19 at least it will work with everything.
- added frontend info on status. 
- added a function for frontend info. Can be used for first reaction text.

### Changes wrt not working tests
- Fixed incorrect imports
- fixed linting errors
- added flask requirement in requirements file

### TODO
- the test fixes do not account for checks in any of the frontends.

### CODE REVIEW

**Comment by pnhofmann** [comment]
+1

**Comment by evamy** [comment]
> +1

^^ This is for ?
@pnhofmann

**Comment by evamy** [comment]
Hi @pnhofmann.
Is it possible to approve and merge this PR.
I have a lot of plugins coming in.

**Comment by pnhofmann** [comment]
Yes sure; Sorry for the delay and really thanks for your work!

**Pull request merged**
