### PR TITLE
Added tell joke

### LINKED ISSUE #120: Jokes chat
Create an action like chat action to tell some jokes. The command to activate the jokes chat should be something like "tell me a joke".

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #120

### CODE REVIEW

**Comment by yashLadha** [comment]
@sukeesh @StefanosChaliasos Review the changes.

**Comment by StefanosChaliasos** [comment]
Can you please resolve the conflicts?

**Comment by yashLadha** [comment]
@StefanosChaliasos Review again Sir?

**Comment by StefanosChaliasos** [comment]
Thanks for your contribution!!!

**Pull request merged**
