### PR TITLE
New Feature: Tic tac toe

### PR DESCRIPTION
**Pull request by DannKim98**
Hi,
Implemented a tic tac toe game from [#659](https://github.com/sukeesh/Jarvis/issues/659) issue.

### CODE REVIEW

**Comment by pnhofmann** [comment]
Code looks fine!
Maybe we could at some sort of simple KI at a later time. But is already a nice plugin and didn't notice any issues.

Unfortunately does not merge. Did you merge an old 'master'-branch?

If there is no merge-conflict (and in this case - if all commits just modify one file, you just added, there definitely isn't), better not merge anything.

You want to take this as an opportunity to try a bit how git works - or shall I fix this merge conflict?

**Comment by DannKim98** [comment]
Sorry, I am not sure if I understand correctly. So should I create a new branch first and then make a pull request of the new branch in order to correct it?

**Comment by pnhofmann** [comment]
> Sorry, I am not sure if I understand correctly.

My mistake... Selected wrong merge-mode in github ;). Nevertheless, merging creates this ugly commits:

` Merge branch 'master' of https://github.com/sukeesh/Jarvis 42b4638 `

And without good use, wouldn't do this. But doesn't really hurt.

What I did notice:

```
 X turn. Choose a position!19
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/phil/git/Jarvis/jarviscli/CmdInterpreter.py", line 234, in try_do
    do(self, s)
  File "/home/phil/git/Jarvis/jarviscli/plugin.py", line 209, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/phil/git/Jarvis/jarviscli/plugins/tic_tac_toe.py", line 87, in game
    if board[s] == '   ':
KeyError: '19'
```

You should probably check bounds of boards-array :).

**Comment by DannKim98** [comment]
Thank you!
I fixed the problem with incorrect input, now should work.

**Comment by pnhofmann** [comment]
Thanks!

**Pull request merged**
