### PR TITLE
Refactor bmi plugin

### PR DESCRIPTION
**Pull request by mbuildingeveryday**
- Improve user interface
- Make Jarvis voice correspond with text 
- Enhance code efficiency

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hmm, still PEP8 errors from last commit

```
$ flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/
jarviscli/plugins/bmi.py:31:18: E231 missing whitespace after ':'
jarviscli/plugins/bmi.py:31:30: E231 missing whitespace after ':'
jarviscli/plugins/bmi.py:59:43: W291 trailing whitespace
jarviscli/plugins/bmi.py:68:58: E999 SyntaxError: invalid syntax
jarviscli/plugins/bmi.py:78:36: W291 trailing whitespace
The command "flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/" exited with 1.
```

But otherwise nothing to complain - nice refactor!

**Comment by mbuildingeveryday** [comment]
I finally figured out PEP8 mode in wingIDE, so whitespace error now is gone.
I think I also fixed the syntaxError, but I'm not sure why Travis CI is still complaining.
Please let me know any errors which I should fix. Thanks.

**Comment by pnhofmann** [comment]
Ah - of course. Should have noticed earlier; BMI has a unit test:

``jarviscli/tests/test_bmi.py``

You renamed ``calc_bmi_i`` and ``calc_bmi_m`` - unit test still trying to call those methods. And that's what is failing. So in theory these methods just need to be renamed in the unit test.

In practice, there is sort of an issue how to pass the 'Jarvis'-instance to a method in a unit test. Because that isn't documented (yep; my fault ;) ). So this would actually be a opportunity for me, to fix this issue.

Right, you can consider your work finished (Thanks by the way!) - and I'll just fix these 4 lines probably tomorrow.

**Comment by mbuildingeveryday** [comment]
Thanks for letting me know the detail of the issue :)

**Comment by pnhofmann** [comment]
Merged! Thanks.

**Pull request merged**
