### PR TITLE
Fix news plugin for bugs

### PR DESCRIPTION
**Pull request by madhavkulkarni1986**
1. urllib.urlopen return bytes. Response should be decded to utf-8 before loading into json format.

Example(failing case):
madhav@ubuntu:~/Projects/Jarvis$ ./jarvis
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
84 plugins loaded 6 plugins disabled. More information: status

~> Hi, what can I do for you?
news
Would you like to configure your own news channel(y/n)
y
I couldn't find news
~> What can i do for you?
news
Would you like to configure your own news channel(y/n)
n
Select Source (1-5):
1: BBC
2: BUZZFEED
3: Google
4: Reddit
5: TechCrunch
1
would you like to set this as your default? (yes/no):
yes
I couldn't find news
~> What can i do for you?

SOLVED WITH THE COMMITr[(added decode('utf-8')]

2. Cover corner cases while taking user input via message "Type index to expand news". Corner cases 0 and (for example) 11 do not work as expected.
made 0 as an option for Exit/Quit. If user inputs index+1(ex: 11 below), reply with "Not valid index"

Example(failing cases):
~> What can i do for you?
news
Would you like to configure your own news channel(y/n)
n
your default news source is bbc-news
Would you like news from this source? (yes/no):
yes
Top News Articles from bbc-news
1: US Congress awaits Mueller report findings
2: May urged to quit to help deal pass
3: Passengers evacuated from Norway cruise
4: More bodies under Cyclone Idai floods - UN
5: Huge fossil discovery made in China
6: Trump vows to 'crush' remaining IS cells
7: Thailand votes in first post-coup election
8: Protests over acquittal in police shooting
9: Streisand criticised for Jackson comments
10: Mossad spy who captured Eichmann dies
Powered by News API. Type NewsAPI to learn more
Type index to expand news

0
I couldn't find news
~> What can i do for you?

--------------------
~> What can i do for you?
news
Would you like to configure your own news channel(y/n)
n
your default news source is bbc-news
Would you like news from this source? (yes/no):
yes
Top News Articles from bbc-news
0: Exit/Quit
1: US Congress awaits Mueller report findings
2: May urged to quit to help deal pass
3: Passengers evacuated from Norway cruise
4: More bodies under Cyclone Idai floods - UN
5: Huge fossil discovery made in China
6: Trump vows to 'crush' remaining IS cells
7: Thailand votes in first post-coup election
8: Protests over acquittal in police shooting
9: Streisand criticised for Jackson comments
10: Mossad spy who captured Eichmann dies
Powered by News API. Type NewsAPI to learn more
Type index to expand news

11
I couldn't find news
~> What can i do for you?

### CODE REVIEW

**Comment by madhavkulkarni1986** [comment]
Sorry for the long commit message

**Comment by appi147** [comment]
@madhavkulkarni1986 We cant merge it, already open in #439 , news is being changed

**Comment by appi147** [comment]
And please dont change your master

**Comment by madhavkulkarni1986** [comment]
Ok, I will wait for #439 to be merged and will have look. And sure, I won't do it in master. Thanks

**Pull request closed without merging**
