### PR TITLE
add support for all platforms in plugin manager

### PR DESCRIPTION
**Pull request by appi147**
I tried to add all supported platforms. I don't know if UNSUPPORTED is a good idea, because we will never call @require(platform=UNSUPPORTED).
ALso, till UNIX is implemented, 
```
@require(platform=LINUX)
@require(platform=WINDOWS)
```
works fine, but 
```
@require(platform=LINUX, platform=WINDOWS)
```
gives error.

### CODE REVIEW

**Comment by appi147** [comment]
closes #531

**Comment by appi147** [comment]
@pnhofmann Merge only if you are satisfied, or you are free to implement in a better way

**Comment by appi147** [comment]
If this is done, most of the work will be done as there won't be error with 
@linux @macos, till perfect version is implemented for win32

**Comment by pnhofmann** [comment]
> @require(platform=LINUX, platform=WINDOWS)
> gives error.

Python won't allow two parameters with same name => So implemented this Syntax:

``@require(platform=[LINUX, WINDOWS])``

**Comment by pnhofmann** [comment]
> I don't know if UNSUPPORTED is a good idea, because we will never call @require(platform=UNSUPPORTED).

Think, this would be the default if no @require is specified. So don't think the UNSUPPORTED variable is required.

**Comment by appi147** [comment]
Looks great

**Pull request merged**
