### PR TITLE
Preparation for PyPi(pip) release

### PR DESCRIPTION
**Pull request by appi147**
@sukeesh @StefanosChaliasos 
I have added necessary  files to create a pip release. Issue #8 
However, package should be uploaded by the author. 
Also, jarvis name is already taken by someone on [PyPi](https://pypi.python.org/pypi?%3Aaction=search&term=jarvis&submit=search) so  

- package name and packages in setup.py should be renamed to different suitable name (e.g. jarvis-assistant etc. which is not already taken) 

- version number should be added in setup.py for a release

If any error or query, please let me know

### CODE REVIEW

**Comment by StefanosChaliasos** [comment]
@sukeesh  can you handle this? I believe you must do it as the author of the project.

**Comment by sukeesh** [comment]
screen shot 2017-06-28 at 9 23 16 pm

When I try to upload, I got this error!

**Comment by appi147** [comment]
Hi @sukeesh does it work now

**Comment by sukeesh** [comment]
I have registered `jarviscli` ( Jarvis Command Line Interface ) as package name. 
Can you please make necessary changes?

and also the classifier for MIT LICENSE is `License :: OSI Approved :: MIT License`

**Comment by appi147** [comment]
Sure!!

**Comment by appi147** [comment]
@sukeesh You have to upload distribution as well as wheel, ottherwise you can not download by using `pip install jarviscli`

**Comment by sukeesh** [comment]
Project structure should be in the following format.

```
Jarvis/
    LICENSE
    README
    setup.py
    jarviscli/
        __init__.py
```
and also `.pyirc` file is compulsory.

[click here
](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html)
I have recently shifted to Mac from Linux. So, I can't make changes to code.

**Comment by appi147** [comment]
@sukeesh 

- .pypirc file should be only with author. It is not to be uploaded to github.

- shall i rename Jarvis/ to jarviscli/ 

- will create __init__.py

-

**Comment by appi147** [comment]
On it

**Comment by appi147** [comment]
@sukeesh renamed it but conflicts should be resolved

**Comment by StefanosChaliasos** [comment]
I will resolve those conflicts.

**Pull request merged**
