### PR TITLE
Automatic testing

### LINKED ISSUE #140: To do automatic testing in Travis

### PR DESCRIPTION
**Pull request by appi147**
Fixes #140

### CODE REVIEW

**Comment by appi147** [comment]
@StefanosChaliasos test TimeIn is failing. I checked locally then also it is failing. Otherwise, this PR can be merged.

**Comment by appi147** [comment]
Fixes #138

**Comment by appi147** [comment]
Build Passing :100:

**Comment by StefanosChaliasos** [comment]
With your solution it's still possible to run the tests manually and in which directory?

**Comment by appi147** [comment]
Tests which have to be manually  run, are placed under tests/test_manual/

Add a __init__.py file in same directory, and all the tests will run as previous

**Pull request merged**
