### PR TITLE
File

### PR DESCRIPTION
**Pull request by umangahuja1**
Review

### CODE REVIEW

**Comment by appi147** [comment]
What  does it do? What I see is that it creates a new directory and moves all the file in it.

**Comment by umangahuja1** [comment]
It create new for and inside it group all files by their extension

_Sent from my Vivo 1601 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
demo2

screenshot from 2017-07-30 13-32-18

**Comment by appi147** [comment]
@umangahuja1 I understood

**Comment by appi147** [comment]
@umangahuja1 Nice work. Could you come up with good command other than `file_organise` because it doesn't seem user-friendly.

**Comment by umangahuja1** [comment]
Suggest anything if you have. Earlier I thought "clean_folder" but that too is not that crisp.

**Comment by StefanosChaliasos** [comment]
Very nice work!

**Comment by umangahuja1** [comment]
thanks.

**Comment by umangahuja1** [comment]
How to solve this conflict now? I have created separate branches

**Comment by appi147** [comment]
No problem. I'll do it

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
Thanks mate. But can you tell me too. I want to get better with git. It is having fun with this project.

**Comment by appi147** [comment]
What I do is
`git fetch upstream`
`git rebase upstream/master`
`git push`

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
Thanks.
And when you commit here, I should pull it in my master and delete the branch with got committed. 
Am I going right.

**Comment by appi147** [comment]
Rebase your master everytime before creating a new branch

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
And when I create two branches at same time like this facebook and file but one got merged before other, then,

**Comment by appi147** [comment]
Rebase

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
