### PR TITLE
New feature: workout program generator

### PR DESCRIPTION
**Pull request by DannKim98**
Implemented one of the features from [#659](https://github.com/sukeesh/Jarvis/issues/659) issue. Workout program generator. Any feedback is welcome)

### CODE REVIEW

**Comment by pnhofmann** [comment]
Hi!

on a quick review, looks good!

Just, please fix PEP8 (output of ``flake8 --select E,W --max-line-length=140 --ignore E722,W503,W504,E128 jarviscli/``):
https://travis-ci.org/sukeesh/Jarvis/jobs/660182405#L390

That's some basic rules (https://www.python.org/dev/peps/pep-0008/) for a standardized and therefore more readable code.
Like in Python: Only use Tabs, because if someone uses Tabs and someone else Spaces, the result would be a real mess ;).

Hint: You could also use ``autopep8 -i YOUR_FILE.py`` - which should automatically fix most issues.

**Comment by DannKim98** [comment]
Thank you! 
I will fix it ;)

**Comment by DannKim98** [comment]
Hi, fixed PEP8. 
Thank you for suggesting autopep8 it helped a lot!

**Comment by pnhofmann** [comment]
Nice, Thanks!

**Pull request merged**
